interface Set {
    title: string;
    vocab: [string, string][];
}

interface AllSetsInterface { id: string, set: Set }

export const AllSets: AllSetsInterface[] = [
    {
        id: "ap-tema-1-las-familias-y-las-comunidades",
        set: {
            title: "Tema 1 - Las familias y las comunidades",
            vocab: [
                [
                    "(bien) educado",
                    "well-mannered"
                ],
                [
                    "agradecer",
                    "to thank"
                ],
                [
                    "apoyar(se)",
                    "to support (each other)"
                ],
                [
                    "criar",
                    "to raise (children)"
                ],
                [
                    "egoísta",
                    "selfish"
                ],
                [
                    "el apodo",
                    "nickname"
                ],
                [
                    "el carácter",
                    "character, personality"
                ],
                [
                    "el nacimiento",
                    "birth"
                ],
                [
                    "el padrastro",
                    "stepfather"
                ],
                [
                    "el prejuicio social",
                    "social prejudice"
                ],
                [
                    "el sexo",
                    "gender"
                ],
                [
                    "el tatarabuelo",
                    "great-great grandfather"
                ],
                [
                    "el yerno",
                    "son-in-law"
                ],
                [
                    "el/la adolescente",
                    "adolescent"
                ],
                [
                    "el/la adulto",
                    "adult"
                ],
                [
                    "el/la bisabuelo",
                    "great-grandfather/mother"
                ],
                [
                    "el/la cuñado",
                    "brother/sister-in-law"
                ],
                [
                    "el/la esposo",
                    "husband/wife"
                ],
                [
                    "el/la hermanastro",
                    "stepbrother/sister"
                ],
                [
                    "el/la hermano (gemelo)",
                    "sister/brother (twin)"
                ],
                [
                    "el/la hijo único",
                    "only child"
                ],
                [
                    "el/la medio hermano",
                    "half brother/sister"
                ],
                [
                    "el/la nieto",
                    "grandson/daughter"
                ],
                [
                    "el/la niña",
                    "child"
                ],
                [
                    "el/la pariente/a",
                    "relative"
                ],
                [
                    "el/la primo",
                    "cousin"
                ],
                [
                    "el/la sobrino",
                    "nephew/niece"
                ],
                [
                    "el/la suegro",
                    "father/mother-in-law"
                ],
                [
                    "el/la tío (abuelo)",
                    "(great) uncle/aunt"
                ],
                [
                    "estricto",
                    "strict"
                ],
                [
                    "exigente",
                    "demanding"
                ],
                [
                    "fastidiado",
                    "fed up/bored"
                ],
                [
                    "heredar",
                    "to inherit"
                ],
                [
                    "honrado",
                    "honest"
                ],
                [
                    "independizarse",
                    "to become independent"
                ],
                [
                    "insoportable",
                    "unbearable"
                ],
                [
                    "la adolescencia",
                    "adolescence"
                ],
                [
                    "la ascendencia",
                    "heritage"
                ],
                [
                    "la autoestima",
                    "self-esteem"
                ],
                [
                    "la brecha generacional",
                    "generational gap"
                ],
                [
                    "la comprensión",
                    "understanding"
                ],
                [
                    "la edad adulta",
                    "adulthood"
                ],
                [
                    "la etnia",
                    "ethnic group"
                ],
                [
                    "la juventud",
                    "youth"
                ],
                [
                    "la madrastra",
                    "stepmother"
                ],
                [
                    "la muerte",
                    "death"
                ],
                [
                    "la niñez",
                    "childhood"
                ],
                [
                    "la nuera",
                    "daughter-in-law"
                ],
                [
                    "la patria",
                    "homeland"
                ],
                [
                    "la raíz",
                    "root"
                ],
                [
                    "la vejez",
                    "old age"
                ],
                [
                    "lamentar",
                    "to regret"
                ],
                [
                    "malcriar",
                    "to spoil"
                ],
                [
                    "maleducado",
                    "ill-mannered"
                ],
                [
                    "mandón/mandona",
                    "bossy"
                ],
                [
                    "mimar",
                    "to pamper"
                ],
                [
                    "mudarse",
                    "to move"
                ],
                [
                    "parecerse",
                    "to resemble, to look like"
                ],
                [
                    "pelear(se)",
                    "to fight (with one another)"
                ]
            ]
        }
    },
    {
        id: "ap-tema-2-vocabulario",
        set: {
            title: "Tema 2 Vocabulario",
            vocab: [
                ["a costa de", "at the expense of"],
                ["a expensas de", "at the expense of; by the effort or sacrifice of someone/something else"],
                ["acudir", "to go to; to turn to"],
                ["ADN (ácido desoxirribonucleico)", "DNA (deoxyribonucleic acid)"],
                ["afrontar", "to confront; to face"],
                ["agotar", "to exhaust; to use up"],
                ["amenaza", "threat"],
                ["artífice", "creator; author; architect"],
                ["asesorar", "to advise; to seek specialized guidance"],
                ["carecer", "to lack; to be without"],
                ["cazar", "to hunt; to chase"],
                ["cobijar", "to shelter; to protect; to cover"],
                ["colgar", "to hang; to be suspended"],
                ["concienciar", "to raise awareness/become concious about a thing"],
                ["crédulo/a", "gullible; credulous"],
                ["dañino/a", "harmful; damaging"],
                ["derramar", "to spill; to pour"],
                ["descomponerse", "to break down; to decay; to fall ill"],
                ["despedazar", "to tear apart; to shatter"],
                ["disponible", "available"],
                ["el aporte", "contribution"],
                ["el callejón", "alley; narrow passage"],
                ["el chivo expiatorio", "scapegoat"],
                ["el desprecio", "contempt; disdain"],
                ["el efecto invernadero", "greenhouse effect"],
                ["el enganche", "addiction; dependency"],
                ["el entorno", "environment; surroundings"],
                ["el fallecimiento", "death; passing"],
                ["el peatón", "pedestrian"],
                ["el semáforo", "traffic light"],
                ["el síndrome de abstinencia", "withdrawal syndrome"],
                ["el siniestro", "accident; disaster"],
                ["el ungüento", "ointment; balm"],
                ["el/la docente", "teacher; instructor"],
                ["enlazado/a", "linked; connected"],
                ["impetuoso/a", "impulsive; passionate"],
                ["imponer", "to impose; to force"],
                ["instaurar", "to establish; to institute"],
                ["la búsqueda", "search; investigation"],
                ["la cacería", "the hunt; hunting"],
                ["la cordillera", "mountain range"],
                ["la mortandad", "high death toll; mortality"],
                ["la senectud", "old age; senescence"],
                ["la sequía", "drought"],
                ["mantener", "to maintain; to preserve"],
                ["marginar", "to marginalize; to isolate"],
                ["milagroso/a", "miraculous; extraordinary"],
                ["mitigar", "to mitigate; to lessen"],
                ["perjudicar", "to harm; to damage"],
                ["plantear", "to propose; to suggest"],
                ["prever", "to foresee; to anticipate"],
                ["quebrar", "to break; to shatter"],
                ["recorrer", "to travel; to go through"],
                ["repercutir", "to have repercussions; to affect"],
                ["retrasar", "to delay; to postpone"],
                ["rumbo a", "heading toward; on the way to"],
                ["salpicar", "to splash; to scatter; to sprinkle"],
            ],
        }
    },
    {
        id: "american-gov-unit-1-review",
        set: {
            title: "American Government – Unit One Review (22 cards)",
            vocab: [
                [
                    "What is government, and how does it maintain order?",
                    "The institutions and officials that make and enforce laws; it maintains order through laws, policing, courts, and public services that resolve disputes and deter harm."
                ],
                [
                    "What is sovereignty, and how do people in the U.S. practice it?",
                    "Supreme authority to rule; in the U.S. sovereignty rests with the people via elections, representation, initiatives/referenda (where applicable), petitions, jury service, protests, and amendments."
                ],
                [
                    "Hobbes’s view of government and law/order?",
                    "In the state of nature life is ‘nasty, brutish, and short’; people form a social contract and need a strong sovereign to impose law and prevent chaos."
                ],
                [
                    "Types of authoritarian governments & how they restrict rights",
                    "Dictatorships, one-party states, military juntas, absolute monarchies, theocracies; restrict by censoring speech/press, banning opposition, rigging elections, arbitrary arrests, and controlling courts."
                ],
                [
                    "Limited government & Magna Carta’s role",
                    "Government with powers restricted by law/constitution; Magna Carta (1215) recognized rule of law, due process, and limits on the king’s power."
                ],
                [
                    "What is representative government?",
                    "A system where citizens elect officials to make laws and govern on their behalf."
                ],
                [
                    "John Locke & Baron de Montesquieu—key ideas",
                    "Locke: natural rights (life, liberty, property), consent of the governed, right to alter/abolish unjust gov. Montesquieu: separation of powers with checks and balances."
                ],
                [
                    "Main ideals of the Declaration of Independence & its primary author",
                    "Equality, unalienable rights, governments exist to secure rights, consent of the governed, right to revolution; primary author: Thomas Jefferson."
                ],
                [
                    "National legislature under the Articles of Confederation",
                    "A unicameral Congress with each state having one vote."
                ],
                [
                    "What was the Connecticut (Great) Compromise?",
                    "It created a bicameral Congress: House by population and Senate with equal representation (two per state)."
                ],
                [
                    "Federalists vs. Antifederalists—main arguments",
                    "Federalists: stronger national government, checks/balances make it safe, supported Constitution. Antifederalists: feared central tyranny, wanted stronger states and a Bill of Rights."
                ],
                [
                    "How does the Preamble exemplify popular sovereignty?",
                    "It begins with “We the People,” stating that the people establish the Constitution and its goals."
                ],
                [
                    "Purpose of Articles I–VI of the Constitution",
                    "I: Legislative branch. II: Executive branch. III: Judicial branch. IV: State relations. V: Amendment process. VI: Supremacy Clause, debts, oaths."
                ],
                [
                    "What is federalism and how does it apply in the U.S.?",
                    "Division of power between national and state governments; some powers are national, some state, and some shared."
                ],
                [
                    "Importance of the Elastic (Necessary & Proper) Clause",
                    "Grants implied powers so Congress can carry out enumerated powers, allowing the system to adapt to new needs."
                ],
                [
                    "Why do checks and balances matter?",
                    "They let each branch limit the others to prevent power concentration and protect liberty."
                ],
                [
                    "Delegated/Expressed vs. Reserved vs. Concurrent powers",
                    "Delegated/Expressed: given to the federal government (e.g., coin money). Reserved: kept by states (10th Amendment; e.g., education). Concurrent: shared (e.g., taxation)."
                ],
                [
                    "Main ways the federal government protects the states",
                    "Guarantees a republican form of government, protection against invasion and domestic violence, and respects state boundaries/representation."
                ],
                [
                    "What are federal grants and why provide them?",
                    "Funds the national government gives to states/localities to support programs and influence policy priorities."
                ],
                [
                    "What is extradition and why important?",
                    "Returning an accused/convicted person to the state where the crime occurred; prevents fugitives from escaping justice."
                ],
                [
                    "What is an interstate compact?",
                    "A formal agreement between states (with congressional consent) to manage shared issues like resources, transportation, or law enforcement."
                ],
                [
                    "How does the Constitution guard against tyranny overall?",
                    "Through limited government, separation of powers, checks and balances, federalism, rule of law, and the Bill of Rights."
                ]
            ]
        }
    },
    {
        id: "honores-3-leccion-1-vocabulario-las-relaciones-personales",
        set: {
            "title": "Lección 1: Vocabulario - Las relaciones personales",
            "vocab": [
                ["Soulmate, kindred spirit", "El alma gemela"],
                ["Friendship", "La amistad"],
                ["Spirit, mood", "El ánimo"],
                ["Gossip", "El chisme"],
                ["(Blind) date", "La cita (a ciegas)"],
                ["Commitment, responsibility", "El compromiso"],
                ["Desire", "El deseo"],
                ["Divorce", "El divorcio"],
                ["(Un)faithfulness", "La (in)fidelidad"],
                ["Marriage", "El matrimonio"],
                ["Couple", "La pareja"],
                ["Risk", "El riesgo"],
                ["To share", "Compartir"],
                ["To trust (in)", "Confiar (en)"],
                ["To rely on, count on", "Contar (o:ue) con"],
                ["To flirt", "Coquetear"],
                ["To leave someone", "Dejar a alguien"],
                ["To stand (someone) up", "Dejar plantado (a alguien)"],
                ["To argue", "Discutir"],
                ["To cheat, to deceive", "Engañar"],
                ["To flirt, to hook up", "Ligar"],
                ["To deserve", "Merecer"],
                ["To break up (with)", "Romper (con)"],
                ["To go out (with)", "Salir (con)"],
                ["Affectionate", "Cariñoso/a"],
                ["Careful", "Cuidadoso/a"],
                ["Insincere", "Falso/a"],
                ["Wonderful", "Genial"],
                ["Funny, pleasant", "Gracioso/a"],
                ["Unforgettable", "Inolvidable"],
                ["Insecure", "Inseguro/a"],
                ["Mature", "Maduro/a"],
                ["Lying, liar", "Mentiroso/a"],
                ["Proud", "Orgulloso/a"],
                ["Secure, confident", "Seguro/a"],
                ["Sensitive", "Sensible"],
                ["Cheap, stingy", "Tacaño/a"],
                ["Stormy", "Tempestuoso/a"],
                ["Shy", "Tímido/a"],
                ["Calm", "Tranquilo/a"],
                ["To fall in love (with)", "Enamorarse (de)"],
                ["To get angry", "Enojarse"],
                ["To be fed up with, to be sick of", "Estar harto/a de"],
                ["To get along well/badly/terribly with", "Llevarse bien/mal/fatal con"],
                ["To hate", "Odiar"],
                ["To become/be annoying", "Poner(se) pesado/a"],
                ["To love or to want", "Querer(se) (e:ie)"],
                ["To feel", "Sentir(se) (e:ie)"],
                ["To dream about", "Soñar con (o:ue)"],
                ["To be jealous (of)", "Tener celos (de)"],
                ["To be ashamed (of)", "Tener vergüenza (de)"],
                ["Overwhelmed", "Agobiado/a"],
                ["Anxious", "Ansioso/a"],
                ["Jealous", "Celoso/a"],
                ["Depressed", "Deprimido/a"],
                ["Upset", "Disgustado/a"],
                ["Excited", "Emocionado/a"],
                ["Angry, mad", "Enojado/a"],
                ["Fleeting", "Pasajero/a"],
                ["Worried (about)", "Preocupado/a (por)"],
                ["To get married (to)", "Casarse (con)"],
                ["To get a divorce (from)", "Divorciarse (de)"],
                ["Married", "Casado/a"],
                ["Divorced", "Divorciado/a"],
                ["Separated", "Separado/a"],
                ["Single", "Soltero/a"],
                ["Widowed", "Viudo/a"]
            ]
        }
    },
    {
        "id": "honores-3-leccion-2-vocabulario-vivir-en-la-ciudad",
        "set": {
            "title": "Lección 2: vocabulario - vivir en la ciudad",
            "vocab": [
                ["Suburbs", "Las afueras"],
                ["The outskirts", "Los alrededores"],
                ["City hall", "El ayuntamiento"],
                ["Neighborhood", "El barrio"],
                ["Mall", "El centro comercial"],
                ["Movie theater", "El cine"],
                ["City", "La ciudad"],
                ["Police station", "La comisaría"],
                ["Dance club", "La discoteca"],
                ["Building", "El edificio"],
                ["(Train/Bus) station", "La estación (de trenes/autobuses)"],
                ["Fire station", "La estación de bomberos"],
                ["Police station", "La estación de policía"],
                ["Parking lot", "El estacionamiento"],
                ["Stadium", "El estadio"],
                ["Subway", "El metro"],
                ["Museum", "El museo"],
                ["(Subway/Bus) stop", "La parada (de metro/de autobús)"],
                ["Square", "La plaza"],
                ["Skyscraper", "El rascacielos"],
                ["Surburb", "El suburbio"],
                ["Housing, home", "La vivienda"],
                ["Sidewalk", "La acera"],
                ["Avenue", "La avenida"],
                ["Street", "La calle"],
                ["City block", "La cuadra"],
                ["Address", "La dirección"],
                ["Corner", "La esquina"],
                ["Sign, billboard", "El letrero"],
                ["Bridge", "El puente"],
                ["Traffic light", "El semáforo"],
                ["Traffic", "El tráfico"],
                ["Public tranportation", "El transporte público"],
                ["To cross", "Cruzar"],
                ["To be lost", "Estar perdido/a"],
                ["To give directions", "Indicar el camino"],
                ["To ask for directions", "Preguntar el camino"],
                ["Mayor", "El/la alcalde(sa)"],
                ["Citizen", "El/la ciudadano/a"],
                ["Driver", "El/la conductor(a)"],
                ["People", "La gente"],
                ["Passenger", "El/la pasejero/a"],
                ["Pedestrian", "El/la peatón/peatona"],
                ["Policeman/woman", "El policía/La mujer policía"],
                ["To go down, to get off (a bus)", "Bajar(se)"],
                ["To build, to contruct", "Construir"],
                ["To talk, to converse", "Conversar"],
                ["To live together, to coexist", "Convivir"],
                ["To take a stroll", "Dar un paseo"],
                ["To take a walk/ride", "Dar una vuelta"],
                ["To take a bike/car/motorcycle ride", "Dar una vuelta en bicicleta/carro/motocicleta"],
                ["To enjoy (oneself)", "Disfrutar(se)"],
                ["To turn", "Doblar"],
                ["To run errands", "Hacer diligencias"],
                ["To stop", "Parar"],
                ["To have a good/bad time", "Pasarlo/la bien/mal"],
                ["To settle, to populate", "Poblar"],
                ["To be located", "Quedar"],
                ["To stay", "Quedarse"],
                ["To travel (around a city)", "Recorrer"],
                ["To relax", "Relajarse"],
                ["To reside", "Residir"],
                ["To get up, to get on (a bus)", "Subir(se)"],
                ["Nightlife", "La vida nocturna"],
                ["Late", "Atrasado/a"],
                ["Everyday", "Cotidiano/a"],
                ["Unexpected", "Inesperado/a"],
                ["Full", "Lleno/a"],
                ["Noisy", "Ruidoso/a"],
                ["Empty", "Vacío/a"]
            ]
        }
    },
    {
        "id": "honores-3-leccion-3-vocabulario-los-medios-de-comunicacion",
        "set": {
            "title": "Lección 3: vocabulario - los medios de comunicación",
            "vocab": [
                ["Event", "El acontecimiento / El evento"],
                ["Current events", "La actualidad"],
                ["Advertisement, commercial", "El anuncio"],
                ["Censorship", "La censura"],
                ["Internet", "El internet"],
                ["Media", "Los medios (de comunicación)"],
                ["Bias", "La parcialidad"],
                ["Advertising", "La publicidad"],
                ["Radio", "El/la radio"],
                ["Radio station", "La radioemisora"],
                ["News report", "El reportaje"],
                ["Website", "El sitio web"],
                ["Season (of a series)", "La temporada"],
                ["To become informed (about)", "Enterarse (de)"],
                ["To surf the web", "Navegar en la red"],
                ["To express an opinion, to think", "Opinar"],
                ["To be biased", "Ser parcial"],
                ["To have a good/bad reputation", "Tener buena/mala fama"],
                ["Up-to-date", "Actualizado/a"],
                ["Prominent", "Destacado/a"],
                ["Live", "En directo/vivo"],
                ["Impartial, unbiased", "Imparcial"],
                ["Influential", "Influyente"],
                ["Actor/actress", "El actor / La actriz"],
                ["Singer", "El/la cantante"],
                ["Film critic", "El/la crítico/a de cine"],
                ["Director", "El/la director(a)"],
                ["(Movie) star (male or female)", "La estrella (de cine)"],
                ["Photographer", "El/la fotógrafo/a"],
                ["Radio announcer", "El/la locutor(a) de radio"],
                ["Listener", "El/la oyente"],
                ["Journalist", "El/la periodista"],
                ["Audience, public", "El público"],
                ["Editor", "El/la redactor(a)"],
                ["Reporter", "El/la reportero/a"],
                ["Television viewer", "El/la televidente"],
                ["Soundtrack", "La banda sonora"],
                ["Network, channel", "La cadena"],
                ["Cinema, movies", "El cine"],
                ["Dubbing", "El doblaje"],
                ["Documentary", "El documental"],
                ["Special effects", "Los efectos especiales"],
                ["Premiere, new movie", "El estreno"],
                ["Screen", "La pantalla"],
                ["Movie", "La película"],
                ["Game show", "El programa de concursos"],
                ["Reality show", "El programa de telerrealidad"],
                ["Subtitles", "Los subtítulos"],
                ["Soap opera", "La telenovela"],
                ["Broadcast", "La transmisión"],
                ["Music video", "El video musical"],
                ["To rehearse", "Ensayar"],
                ["To entertain", "Entretener"],
                ["To interview", "Entrevistar"],
                ["To shoot (a movie)", "Rodar (o:ue)"],
                ["To record", "Grabar"],
                ["To broadcast", "Transmitir"],
                ["Horoscope", "El horóscopo"],
                ["Freedom of the press", "La libertad de prensa"],
                ["Local/international/national news", "Las noticias locales/internacionales/nacionales"],
                ["Newspaper", "El periódico / El diario"],
                ["Front page, cover", "La portada"],
                ["(Sensationalist) press", "La prensa (sensacionalista)"],
                ["Magazine", "La revista"],
                ["Lifestyle section", "La sección de sociedad"],
                ["Sports section", "La sección deportiva"],
                ["Comic strip", "La tira cómica"],
                ["Headline", "El titular"],
                ["To research, to investigate", "Investigar"],
                ["To publish", "Publicar"],
                ["To subscribe (to)", "Suscribirse (a)"]
            ]
        }
    },
    {
        "id": "honores-3-leccion-4-vocabulario-en-familia",
        "set": {
            "title": "Lección 4: vocabulario - En familia",
            "vocab": [
                ["Ancestor", "El antepasado"],
                ["Great-grandfather", "El bisabuelo"],
                ["Great-grandmother", "La bisabuela"],
                ["Brother-in-law", "El cuñado"],
                ["Sister-in-law", "La cuñada"],
                ["Husband", "El esposo"],
                ["Wife", "La esposa"],
                ["Twin (brother)", "El gemelo"],
                ["Twin (sister)", "La gemela"],
                ["Stepbrother", "El hermanastro"],
                ["Stepsister", "La hermanastra"],
                ["Only child (son)", "El hijo único"],
                ["Only child (daughter)", "La hija única"],
                ["Stepmother", "La madrastra"],
                ["Half-brother", "El medio hermano"],
                ["Half-sister", "La media hermana"],
                ["Grandson", "El nieto"],
                ["Granddaughter", "La nieta"],
                ["Daughter-in-law", "La nuera"],
                ["Stepfather", "El padrastro"],
                ["Relative", "El/la pariente"],
                ["Cousin (male)", "El primo"],
                ["Cousin (female)", "La prima"],
                ["Nephew", "El sobrino"],
                ["Niece", "La sobrina"],
                ["Father-in-law", "El suegro"],
                ["Mother-in-law", "La suegra"],
                ["(Great) uncle", "El tío (abuelo)"],
                ["(Great) aunt", "La tía (abuela)"],
                ["Son-in-law", "El yerno"],
                ["Adolescence", "La adolescencia"],
                ["Adolescent (male)", "El adolescente"],
                ["Adolescent (female)", "La adolescente"],
                ["Adult (male)", "El adulto"],
                ["Adult (female)", "La adulta"],
                ["Adulthood", "La edad adulta"],
                ["Youth", "La juventud"],
                ["Death", "La muerte"],
                ["Birth", "El nacimiento"],
                ["Childhood", "La niñez"],
                ["Child (boy)", "El niño"],
                ["Child (girl)", "La niña"],
                ["Old age", "La vejez"],
                ["To thank", "Agradecer"],
                ["To support (each other)", "Apoyar(se)"],
                ["To raise (children)", "Criar"],
                ["To become independent", "Independizar(se)"],
                ["To regret", "Lamentar"],
                ["To spoil", "Malcriar"],
                ["To pamper", "Mimar"],
                ["To move (homes)", "Mudar(se)"],
                ["To fight with (one another)", "Pelear(se) con"],
                ["To complain about", "Quejar(se) de"],
                ["To scold", "Regañar"],
                ["To respect", "Respetar"],
                ["To overcome", "Superar"],
                ["Nickname", "El apodo"],
                ["Heritage", "La ascendencia"],
                ["Self-esteem", "La autoestima"],
                ["Generation gap", "La brecha generacional"],
                ["Understanding", "La comprensión"],
                ["Homeland", "La patria"],
                ["Social prejudice", "El perjuicio social"],
                ["Root", "La raíz"],
                ["Gender", "El sexo / el género"],
                ["To inherit", "Heredar"],
                ["To resemble, to look like", "Parecer(se)"],
                ["To become true", "Realizar(se)"],
                ["To survive", "Sobrevivir"],
                ["Character, personality", "Carácter"],
                ["Well-mannered (male)", "Bien educado"],
                ["Well-mannered (female)", "Bien educada"],
                ["Selfish", "Egoísta"],
                ["Strict (male)", "Estricto"],
                ["Strict (female)", "Estricta"],
                ["Demanding", "Exigente"],
                ["Honest (male)", "Honrado"],
                ["Honest (female)", "Honrada"],
                ["Unbearable", "Insoportable"],
                ["Ill-mannered (male)", "Maleducado"],
                ["Ill-mannered (female)", "Maleducada"],
                ["Bossy (male)", "Mandón"],
                ["Bossy (female)", "Mandona"],
                ["Rebellious", "Rebelde"],
                ["Submissive (male)", "Sumiso"],
                ["Submissive (female)", "Sumisa"],
                ["Close-knit", "Unido/Unida"]
            ]
        }
    },
    {
        "id": "honores-3-leccion-5-vocabulario-nuestro-mundo",
        "set": {
            "title": "Lección 5: vocabulario - Nuestro mundo",
            "vocab": [
                ["Tree", "El árbol"],
                ["Forest", "El bosque"],
                ["Mountain range", "La cordillera"],
                ["Coast", "La costa"],
                ["Desert", "El desierto"],
                ["Moon", "La luna"],
                ["Sea", "El mar"],
                ["Landscape, scenery", "El paisaje"],
                ["River", "El río"],
                ["(Tropical) rainforest", "La selva (tropical)"],
                ["Sun", "El sol"],
                ["Land, earth", "La tierra"],
                ["Outdoors", "El aire libre"],
                ["Scant, scarce", "Escaso"],
                ["Drinkable", "Potable"],
                ["Protected (male)", "Protegido"],
                ["Protected (female)", "Protegida"],
                ["Pure, clean (male)", "Puro"],
                ["Pure, clean (female)", "Pura"],
                ["Dry (male)", "Seco"],
                ["Dry (female)", "Seca"],
                ["Eagle", "El águila (f.)"],
                ["Bird", "El ave / El pájaro"],
                ["Whale", "La ballena"],
                ["Endangered species", "El especie en peligro (de extinción)"],
                ["Seal", "La foca"],
                ["Lizard", "El lagarto"],
                ["Lion", "El león"],
                ["Wolf", "El lobo"],
                ["Monkey", "El mono"],
                ["Bear", "El oso"],
                ["Fish", "El pez"],
                ["Snake", "La serpiente"],
                ["Tiger", "El tigre"],
                ["(Sea) turtle", "La tortuga (marina)"],
                ["Warming", "El calentamiento"],
                ["Erosion", "La erosión"],
                ["Hurricane", "El huracán"],
                ["Fire", "El incendio"],
                ["Flood", "La inundación"],
                ["Rain", "La lluvia"],
                ["Drought", "La sequía"],
                ["Earthquake", "El terremoto"],
                ["Trash", "La basura"],
                ["Ozone layer", "La capa de ozono"],
                ["Fuel", "El combustible"],
                ["Energy consumption", "El consumo de energía"],
                ["Pollution", "La contaminación"],
                ["Deforestation", "La deforestación"],
                ["Development", "El desarrollo"],
                ["Energy (wind, nuclear, renewable, solar)", "La energía (eólica, nuclear, renovable, solar)"],
                ["Source", "La fuente"],
                ["Environment", "El medio ambiente"],
                ["Danger", "El peligro"],
                ["Oil", "El petróleo"],
                ["Future", "El porvenir"],
                ["Resources", "Los recursos"],
                ["Smog", "El smog"],
                ["Harmful (male)", "Dañino"],
                ["Harmful (female)", "Dañina"],
                ["Disposable", "Desechable"],
                ["Hybrid (male)", "Híbrido"],
                ["Hybrid (female)", "Híbrida"],
                ["Renewable", "Renovable"],
                ["Toxic (male)", "Tóxico"],
                ["Toxic (female)", "Tóxica"],
                ["To use up", "Agotar"],
                ["To put up with, to tolerate", "Aguantar"],
                ["To threaten", "Amenazar"],
                ["To hunt", "Cazar"],
                ["To preserve", "Conservar"],
                ["To infect, to be contagious", "Contagiar"],
                ["To pollute", "Contaminar"],
                ["To disappear", "Desaparecer"],
                ["To destroy", "Destruir"],
                ["To throw away", "Echar"],
                ["To get worse", "Empeorar"],
                ["To become extinct", "Extinguir(se)"],
                ["To waste", "Malgastar"],
                ["To improve", "Mejorar"],
                ["To prevent", "Prevenir (e→ie)"],
                ["To protect", "Proteger"],
                ["To solve, resolve", "Resolver (o→ue)"],
                ["To breathe", "Respirar"],
                ["To urbanize", "Urbanizar"]
            ]
        }
    },
    {
        "id": "honores-3-leccion-6-vocabulario-creencias-e-ideologias",
        "set": {
            "title": "Lección 6: vocabulario - Creencias e ideologías",
            "vocab": [
                ["Human rights", "Los derechos humanos"],
                ["Civil disobedience", "La desobediencia civil"],
                ["Equality", "La igualdad"],
                ["Inequality", "La desigualdad"],
                ["Judge (male)", "El juez"],
                ["Judge (female)", "La jueza"],
                ["Justice", "La justicia"],
                ["Injustice", "La injusticia"],
                ["Freedom", "La libertad"],
                ["Struggle, fight", "La lucha"],
                ["Court", "El tribunal"],
                ["To abuse", "Abusar"],
                ["To pass a law", "Aprobar (o→ue) una ley"],
                ["To summon", "Convocar"],
                ["To defend", "Defender (e→ie)"],
                ["To abolish", "Derogar"],
                ["To imprison", "Encarcelar"],
                ["To judge", "Juzgar"],
                ["Illiterate", "Analfabeto/a"],
                ["Equal", "Igual"],
                ["Unequal", "Desigual"],
                ["Fair", "Justo/a"],
                ["Unfair", "Injusto/a"],
                ["Oppressed", "Oprimido/a"],
                ["Threat", "La amenaza"],
                ["Weapon", "El arma (f.)"],
                ["Scandal", "El escándalo"],
                ["Security, safety", "La seguridad"],
                ["Insecurity, lack of safety", "La inseguridad"],
                ["Fear", "El temor"],
                ["Terrorism", "El terrorismo"],
                ["Violence", "La violencia"],
                ["To blackmail", "Chantajear"],
                ["To destroy", "Destrozar"],
                ["To spy", "Espiar"],
                ["To flee", "Huir"],
                ["To fight", "Pelear"],
                ["To kidnap, to hijack", "Secuestrar"],
                ["Abuse", "El abuso"],
                ["Navy", "La armada"],
                ["Flag", "La bandera"],
                ["Belief", "La creencia"],
                ["Cruelty", "La crueldad"],
                ["Democracy", "La democracia"],
                ["Dictatorship", "La dictadura"],
                ["Army", "El ejército"],
                ["Government", "El gobierno"],
                ["(Civil) war", "La guerra (civil)"],
                ["Political party", "El partido político"],
                ["Peace", "La paz"],
                ["Power", "El poder"],
                ["Politics", "La política"],
                ["Foreign relations", "Las relaciones exteriores"],
                ["Victory", "La victoria"],
                ["To devote oneself to", "Dedicar(se) a"],
                ["To elect", "Elegir (e→i)"],
                ["To win elections", "Ganar las elecciones"],
                ["To lose elections", "Perder (e→ie) las elecciones"],
                ["To govern", "Gobernar"],
                ["To influence", "Influir"],
                ["To vote", "Votar"],
                ["Conservative (male)", "Conservador"],
                ["Conservative (female)", "Conservadora"],
                ["Liberal", "Liberal"],
                ["Peaceful (male)", "Pacífico"],
                ["Peaceful (female)", "Pacífica"],
                ["Pacifist", "Pacifista"],
                ["Lawyer (male)", "El abogado"],
                ["Lawyer (female)", "La abogada"],
                ["Activist (male)", "El activista"],
                ["Activist (female)", "La activista"],
                ["Thief (male)", "El ladrón"],
                ["Thief (female)", "La ladrona"],
                ["Demonstrator (male)", "El manifestante"],
                ["Demonstrator (female)", "La manifestante"],
                ["Politician (male)", "El político"],
                ["Politician (female)", "La política"],
                ["President (male)", "El presidente"],
                ["President (female)", "La presidenta"],
                ["Terrorist (male)", "El terrorista"],
                ["Terrorist (female)", "La terrorista"],
                ["Victim", "La víctima"]
            ]
        }
    },
    {
        "id": "honores-3-el-arte-vocabulario",
        "set": {
            "title": "El arte - Vocabulario",
            "vocab": [
                ["Watercolor", "La acuarela"],
                ["Caricature", "La caricatura"],
                ["Nature", "La naturaleza"],
                ["Still-life", "La naturaleza muerta"],
                ["Outside", "Afuera"],
                ["Portrait", "El retrato"],
                ["Self-portrait", "El autorretrato"],
                ["Landscape", "El paisaje"],
                ["To design", "Diseñar"],
                ["The design", "El diseño"],
                ["Metamorphic art", "El arte de metamorfosis"],
                ["The drawing", "El dibujo"],
                ["To draw", "Dibujar"],
                ["The mural", "El mural"],
                ["Religious art", "El arte religioso"],
                ["Painting", "El cuadro, la pintura"],
                ["Oil painting", "La pintura al óleo"],
                ["Mythology", "La mitología"],
                ["Mythological", "Mitológico/a"],
                ["The focus", "El foco"],
                ["To focus on", "Enfocarse en"],
                ["The image(s)", "La imagen / Las imágenes"],
                ["The goal", "La meta"],
                ["The objective", "El objetivo"],
                ["Death", "La muerte"],
                ["The cross", "La cruz"],
                ["The era", "La época"],
                ["The topic, theme", "El tema"],
                ["To try / To deal with", "Tratar (de)"],
                ["Human beings", "Los seres humanos"],
                ["The subject", "El sujeto"],
                ["Bodies", "Los cuerpos"],
                ["Texture", "La textura"],
                ["Pastels", "Los pasteles"],
                ["Bright", "Brillante"],
                ["Colorful", "Colorido/a"],
                ["Dark", "Oscuro/a"],
                ["Strong", "Fuerte"],
                ["Light (color)", "Claro/a"],
                ["A pale/fair woman", "Una mujer pálida"],
                ["Light and shadows", "Luz y sombras"],
                ["Space", "El espacio"],
                ["Similarity", "La semejanza"],
                ["The face", "La cara"],
                ["The figures", "Las figuras"],
                ["Modern", "Moderno"],
                ["Different, strange", "Distinto / raro / extraño"],
                ["Classical", "Clásico"],
                ["The details", "Los detalles"],
                ["Background", "El fondo"],
                ["Foreground", "El primer plano"],
                ["The feeling", "El sentimiento"],
                ["The difference", "La diferencia"],
                ["To move, affect deeply", "Conmocionar"],
                ["Round", "Redondo/a"],
                ["Bold", "Audaz"],
                ["The illustration", "La ilustración"],
                ["To illustrate", "Ilustrar"],
                ["To try", "Intentar"],
                ["To carry out, execute", "Llevar a cabo"],
                ["The sponsor, patron", "El patrón"],
                ["To sponsor", "Patrocinar"],
                ["To realize, execute, fulfill", "Realizar"],
                ["To feel proud of", "Sentirse orgulloso de"],
                ["Sadness", "La tristeza"],
                ["The art exhibit", "La exhibición de arte"],
                ["A work of art", "Una obra de arte"],
                ["A masterpiece", "Una obra maestra"],
                ["Old, antique", "Antiguo/a"],
                ["Contemporary", "Contemporáneo/a"],
                ["The line", "La línea"],
                ["Brushstrokes", "Las pinceladas"],
                ["Brushes", "Los pinceles"],
                ["Life", "La vida"],
                ["Sky / Heaven", "El cielo"]
            ]
        }
    },
    {
        id: "honores-3-todas-las-palabras-de-vocabulario",
        set: {
            title: "Todas Las Palabras De Vocabulario de Español 3 Honores",
            vocab: [
                ["El alma gemela", "Soulmate, kindred spirit"],
                ["La amistad", "Friendship"],
                ["El ánimo", "Spirit, mood"],
                ["El chisme", "Gossip"],
                ["La cita (a ciegas)", "(Blind) date"],
                ["El compromiso", "Commitment, responsibility"],
                ["El deseo", "Desire"],
                ["El divorcio", "Divorce"],
                ["La (in)fidelidad", "(Un)faithfulness"],
                ["El matrimonio", "Marriage"],
                ["La pareja", "Couple"],
                ["El riesgo", "Risk"],
                ["Compartir", "To share"],
                ["Confiar (en)", "To trust (in)"],
                ["Contar (o:ue) con", "To rely on, count on"],
                ["Coquetear", "To flirt"],
                ["Dejar a alguien", "To leave someone"],
                ["Dejar plantado (a alguien)", "To stand (someone) up"],
                ["Discutir", "To argue"],
                ["Engañar", "To cheat, to deceive"],
                ["Ligar", "To flirt, to hook up"],
                ["Merecer", "To deserve"],
                ["Romper (con)", "To break up (with)"],
                ["Salir (con)", "To go out (with)"],
                ["Cariñoso/a", "Affectionate"],
                ["Cuidadoso/a", "Careful"],
                ["Falso/a", "Insincere"],
                ["Genial", "Wonderful"],
                ["Gracioso/a", "Funny, pleasant"],
                ["Inolvidable", "Unforgettable"],
                ["Inseguro/a", "Insecure"],
                ["Maduro/a", "Mature"],
                ["Mentiroso/a", "Lying, liar"],
                ["Orgulloso/a", "Proud"],
                ["Seguro/a", "Secure, confident"],
                ["Sensible", "Sensitive"],
                ["Tacaño/a", "Cheap, stingy"],
                ["Tempestuoso/a", "Stormy"],
                ["Tímido/a", "Shy"],
                ["Tranquilo/a", "Calm"],
                ["Enamorarse (de)", "To fall in love (with)"],
                ["Enojarse", "To get angry"],
                ["Estar harto/a de", "To be fed up with, to be sick of"],
                ["Llevarse bien/mal/fatal con", "To get along well/badly/terribly with"],
                ["Odiar", "To hate"],
                ["Poner(se) pesado/a", "To become/be annoying"],
                ["Querer(se) (e:ie)", "To love or to want"],
                ["Sentir(se) (e:ie)", "To feel"],
                ["Soñar con (o:ue)", "To dream about"],
                ["Tener celos (de)", "To be jealous (of)"],
                ["Tener vergüenza (de)", "To be ashamed (of)"],
                ["Agobiado/a", "Overwhelmed"],
                ["Ansioso/a", "Anxious"],
                ["Celoso/a", "Jealous"],
                ["Deprimido/a", "Depressed"],
                ["Disgustado/a", "Upset"],
                ["Emocionado/a", "Excited"],
                ["Enojado/a", "Angry, mad"],
                ["Pasajero/a", "Fleeting"],
                ["Preocupado/a (por)", "Worried (about)"],
                ["Casarse (con)", "To get married (to)"],
                ["Divorciarse (de)", "To get a divorce (from)"],
                ["Casado/a", "Married"],
                ["Divorciado/a", "Divorced"],
                ["Separado/a", "Separated"],
                ["Soltero/a", "Single"],
                ["Viudo/a", "Widowed"],
                ["Las afueras", "Suburbs"],
                ["Los alrededores", "The outskirts"],
                ["El ayuntamiento", "City hall"],
                ["El barrio", "Neighborhood"],
                ["El centro comercial", "Mall"],
                ["El cine", "Movie theater"],
                ["La ciudad", "City"],
                ["La comisaría", "Police station"],
                ["La discoteca", "Dance club"],
                ["El edificio", "Building"],
                ["La estación (de trenes/autobuses)", "(Train/Bus) station"],
                ["La estación de bomberos", "Fire station"],
                ["La estación de policía", "Police station"],
                ["El estacionamiento", "Parking lot"],
                ["El estadio", "Stadium"],
                ["El metro", "Subway"],
                ["El museo", "Museum"],
                ["La parada (de metro/de autobús)", "(Subway/Bus) stop"],
                ["La plaza", "Square"],
                ["El rascacielos", "Skyscraper"],
                ["El suburbio", "Surburb"],
                ["La vivienda", "Housing, home"],
                ["La acera", "Sidewalk"],
                ["La avenida", "Avenue"],
                ["La calle", "Street"],
                ["La cuadra", "City block"],
                ["La dirección", "Address"],
                ["La esquina", "Corner"],
                ["El letrero", "Sign, billboard"],
                ["El puente", "Bridge"],
                ["El semáforo", "Traffic light"],
                ["El tráfico", "Traffic"],
                ["El transporte público", "Public tranportation"],
                ["Cruzar", "To cross"],
                ["Estar perdido/a", "To be lost"],
                ["Indicar el camino", "To give directions"],
                ["Preguntar el camino", "To ask for directions"],
                ["El/la alcalde(sa)", "Mayor"],
                ["El/la ciudadano/a", "Citizen"],
                ["El/la conductor(a)", "Driver"],
                ["La gente", "People"],
                ["El/la pasejero/a", "Passenger"],
                ["El/la peatón/peatona", "Pedestrian"],
                ["El policía/La mujer policía", "Policeman/woman"],
                ["Bajar(se)", "To go down, to get off (a bus)"],
                ["Construir", "To build, to contruct"],
                ["Conversar", "To talk, to converse"],
                ["Convivir", "To live together, to coexist"],
                ["Dar un paseo", "To take a stroll"],
                ["Dar una vuelta", "To take a walk/ride"],
                ["Dar una vuelta en bicicleta/carro/motocicleta", "To take a bike/car/motorcycle ride"],
                ["Disfrutar(se)", "To enjoy (oneself)"],
                ["Doblar", "To turn"],
                ["Hacer diligencias", "To run errands"],
                ["Parar", "To stop"],
                ["Pasarlo/la bien/mal", "To have a good/bad time"],
                ["Poblar", "To settle, to populate"],
                ["Quedar", "To be located"],
                ["Quedarse", "To stay"],
                ["Recorrer", "To travel (around a city)"],
                ["Relajarse", "To relax"],
                ["Residir", "To reside"],
                ["Subir(se)", "To get up, to get on (a bus)"],
                ["La vida nocturna", "Nightlife"],
                ["Atrasado/a", "Late"],
                ["Cotidiano/a", "Everyday"],
                ["Inesperado/a", "Unexpected"],
                ["Lleno/a", "Full"],
                ["Ruidoso/a", "Noisy"],
                ["Vacío/a", "Empty"],
                ["El acontecimiento / El evento", "Event"],
                ["La actualidad", "Current events"],
                ["El anuncio", "Advertisement, commercial"],
                ["La censura", "Censorship"],
                ["El internet", "Internet"],
                ["Los medios (de comunicación)", "Media"],
                ["La parcialidad", "Bias"],
                ["La publicidad", "Advertising"],
                ["El/la radio", "Radio"],
                ["La radioemisora", "Radio station"],
                ["El reportaje", "News report"],
                ["El sitio web", "Website"],
                ["La temporada", "Season (of a series)"],
                ["Enterarse (de)", "To become informed (about)"],
                ["Navegar en la red", "To surf the web"],
                ["Opinar", "To express an opinion, to think"],
                ["Ser parcial", "To be biased"],
                ["Tener buena/mala fama", "To have a good/bad reputation"],
                ["Actualizado/a", "Up-to-date"],
                ["Destacado/a", "Prominent"],
                ["En directo/vivo", "Live"],
                ["Imparcial", "Impartial, unbiased"],
                ["Influyente", "Influential"],
                ["El actor / La actriz", "Actor/actress"],
                ["El/la cantante", "Singer"],
                ["El/la crítico/a de cine", "Film critic"],
                ["El/la director(a)", "Director"],
                ["La estrella (de cine)", "(Movie) star (male or female)"],
                ["El/la fotógrafo/a", "Photographer"],
                ["El/la locutor(a) de radio", "Radio announcer"],
                ["El/la oyente", "Listener"],
                ["El/la periodista", "Journalist"],
                ["El público", "Audience, public"],
                ["El/la redactor(a)", "Editor"],
                ["El/la reportero/a", "Reporter"],
                ["El/la televidente", "Television viewer"],
                ["La banda sonora", "Soundtrack"],
                ["La cadena", "Network, channel"],
                ["El cine", "Cinema, movies"],
                ["El doblaje", "Dubbing"],
                ["El documental", "Documentary"],
                ["Los efectos especiales", "Special effects"],
                ["El estreno", "Premiere, new movie"],
                ["La pantalla", "Screen"],
                ["La película", "Movie"],
                ["El programa de concursos", "Game show"],
                ["El programa de telerrealidad", "Reality show"],
                ["Los subtítulos", "Subtitles"],
                ["La telenovela", "Soap opera"],
                ["La transmisión", "Broadcast"],
                ["El video musical", "Music video"],
                ["Ensayar", "To rehearse"],
                ["Entretener", "To entertain"],
                ["Entrevistar", "To interview"],
                ["Rodar (o:ue)", "To shoot (a movie)"],
                ["Grabar", "To record"],
                ["Transmitir", "To broadcast"],
                ["El horóscopo", "Horoscope"],
                ["La libertad de prensa", "Freedom of the press"],
                ["Las noticias locales/internacionales/nacionales", "Local/international/national news"],
                ["El periódico / El diario", "Newspaper"],
                ["La portada", "Front page, cover"],
                ["La prensa (sensacionalista)", "(Sensationalist) press"],
                ["La revista", "Magazine"],
                ["La sección de sociedad", "Lifestyle section"],
                ["La sección deportiva", "Sports section"],
                ["La tira cómica", "Comic strip"],
                ["El titular", "Headline"],
                ["Investigar", "To research, to investigate"],
                ["Publicar", "To publish"],
                ["Suscribirse (a)", "To subscribe (to)"],
                ["El antepasado", "Ancestor"],
                ["El bisabuelo", "Great-grandfather"],
                ["La bisabuela", "Great-grandmother"],
                ["El cuñado", "Brother-in-law"],
                ["La cuñada", "Sister-in-law"],
                ["El esposo", "Husband"],
                ["La esposa", "Wife"],
                ["El gemelo", "Twin (brother)"],
                ["La gemela", "Twin (sister)"],
                ["El hermanastro", "Stepbrother"],
                ["La hermanastra", "Stepsister"],
                ["El hijo único", "Only child (son)"],
                ["La hija única", "Only child (daughter)"],
                ["La madrastra", "Stepmother"],
                ["El medio hermano", "Half-brother"],
                ["La media hermana", "Half-sister"],
                ["El nieto", "Grandson"],
                ["La nieta", "Granddaughter"],
                ["La nuera", "Daughter-in-law"],
                ["El padrastro", "Stepfather"],
                ["El/la pariente", "Relative"],
                ["El primo", "Cousin (male)"],
                ["La prima", "Cousin (female)"],
                ["El sobrino", "Nephew"],
                ["La sobrina", "Niece"],
                ["El suegro", "Father-in-law"],
                ["La suegra", "Mother-in-law"],
                ["El tío (abuelo)", "(Great) uncle"],
                ["La tía (abuela)", "(Great) aunt"],
                ["El yerno", "Son-in-law"],
                ["La adolescencia", "Adolescence"],
                ["El adolescente", "Adolescent (male)"],
                ["La adolescente", "Adolescent (female)"],
                ["El adulto", "Adult (male)"],
                ["La adulta", "Adult (female)"],
                ["La edad adulta", "Adulthood"],
                ["La juventud", "Youth"],
                ["La muerte", "Death"],
                ["El nacimiento", "Birth"],
                ["La niñez", "Childhood"],
                ["El niño", "Child (boy)"],
                ["La niña", "Child (girl)"],
                ["La vejez", "Old age"],
                ["Agradecer", "To thank"],
                ["Apoyar(se)", "To support (each other)"],
                ["Criar", "To raise (children)"],
                ["Independizar(se)", "To become independent"],
                ["Lamentar", "To regret"],
                ["Malcriar", "To spoil"],
                ["Mimar", "To pamper"],
                ["Mudar(se)", "To move (homes)"],
                ["Pelear(se) con", "To fight with (one another)"],
                ["Quejar(se) de", "To complain about"],
                ["Regañar", "To scold"],
                ["Respetar", "To respect"],
                ["Superar", "To overcome"],
                ["El apodo", "Nickname"],
                ["La ascendencia", "Heritage"],
                ["La autoestima", "Self-esteem"],
                ["La brecha generacional", "Generation gap"],
                ["La comprensión", "Understanding"],
                ["La patria", "Homeland"],
                ["El perjuicio social", "Social prejudice"],
                ["La raíz", "Root"],
                ["El sexo / el género", "Gender"],
                ["Heredar", "To inherit"],
                ["Parecer(se)", "To resemble, to look like"],
                ["Realizar(se)", "To become true"],
                ["Sobrevivir", "To survive"],
                ["Carácter", "Character, personality"],
                ["Bien educado", "Well-mannered (male)"],
                ["Bien educada", "Well-mannered (female)"],
                ["Egoísta", "Selfish"],
                ["Estricto", "Strict (male)"],
                ["Estricta", "Strict (female)"],
                ["Exigente", "Demanding"],
                ["Honrado", "Honest (male)"],
                ["Honrada", "Honest (female)"],
                ["Insoportable", "Unbearable"],
                ["Maleducado", "Ill-mannered (male)"],
                ["Maleducada", "Ill-mannered (female)"],
                ["Mandón", "Bossy (male)"],
                ["Mandona", "Bossy (female)"],
                ["Rebelde", "Rebellious"],
                ["Sumiso", "Submissive (male)"],
                ["Sumisa", "Submissive (female)"],
                ["Unido/Unida", "Close-knit"],
                ["El árbol", "Tree"],
                ["El bosque", "Forest"],
                ["La cordillera", "Mountain range"],
                ["La costa", "Coast"],
                ["El desierto", "Desert"],
                ["La luna", "Moon"],
                ["El mar", "Sea"],
                ["El paisaje", "Landscape, scenery"],
                ["El río", "River"],
                ["La selva (tropical)", "(Tropical) rainforest"],
                ["El sol", "Sun"],
                ["La tierra", "Land, earth"],
                ["El aire libre", "Outdoors"],
                ["Escaso", "Scant, scarce"],
                ["Potable", "Drinkable"],
                ["Protegido", "Protected (male)"],
                ["Protegida", "Protected (female)"],
                ["Puro", "Pure, clean (male)"],
                ["Pura", "Pure, clean (female)"],
                ["Seco", "Dry (male)"],
                ["Seca", "Dry (female)"],
                ["El águila (f.)", "Eagle"],
                ["El ave / El pájaro", "Bird"],
                ["La ballena", "Whale"],
                ["El especie en peligro (de extinción)", "Endangered species"],
                ["La foca", "Seal"],
                ["El lagarto", "Lizard"],
                ["El león", "Lion"],
                ["El lobo", "Wolf"],
                ["El mono", "Monkey"],
                ["El oso", "Bear"],
                ["El pez", "Fish"],
                ["La serpiente", "Snake"],
                ["El tigre", "Tiger"],
                ["La tortuga (marina)", "(Sea) turtle"],
                ["El calentamiento", "Warming"],
                ["La erosión", "Erosion"],
                ["El huracán", "Hurricane"],
                ["El incendio", "Fire"],
                ["La inundación", "Flood"],
                ["La lluvia", "Rain"],
                ["La sequía", "Drought"],
                ["El terremoto", "Earthquake"],
                ["La basura", "Trash"],
                ["La capa de ozono", "Ozone layer"],
                ["El combustible", "Fuel"],
                ["El consumo de energía", "Energy consumption"],
                ["La contaminación", "Pollution"],
                ["La deforestación", "Deforestation"],
                ["El desarrollo", "Development"],
                ["La energía (eólica, nuclear, renovable, solar)", "Energy (wind, nuclear, renewable, solar)"],
                ["La fuente", "Source"],
                ["El medio ambiente", "Environment"],
                ["El peligro", "Danger"],
                ["El petróleo", "Oil"],
                ["El porvenir", "Future"],
                ["Los recursos", "Resources"],
                ["El smog", "Smog"],
                ["Dañino", "Harmful (male)"],
                ["Dañina", "Harmful (female)"],
                ["Desechable", "Disposable"],
                ["Híbrido", "Hybrid (male)"],
                ["Híbrida", "Hybrid (female)"],
                ["Renovable", "Renewable"],
                ["Tóxico", "Toxic (male)"],
                ["Tóxica", "Toxic (female)"],
                ["Agotar", "To use up"],
                ["Aguantar", "To put up with, to tolerate"],
                ["Amenazar", "To threaten"],
                ["Cazar", "To hunt"],
                ["Conservar", "To preserve"],
                ["Contagiar", "To infect, to be contagious"],
                ["Contaminar", "To pollute"],
                ["Desaparecer", "To disappear"],
                ["Destruir", "To destroy"],
                ["Echar", "To throw away"],
                ["Empeorar", "To get worse"],
                ["Extinguir(se)", "To become extinct"],
                ["Malgastar", "To waste"],
                ["Mejorar", "To improve"],
                ["Prevenir (e→ie)", "To prevent"],
                ["Proteger", "To protect"],
                ["Resolver (o→ue)", "To solve, resolve"],
                ["Respirar", "To breathe"],
                ["Urbanizar", "To urbanize"],
                ["Los derechos humanos", "Human rights"],
                ["La desobediencia civil", "Civil disobedience"],
                ["La igualdad", "Equality"],
                ["La desigualdad", "Inequality"],
                ["El juez", "Judge (male)"],
                ["La jueza", "Judge (female)"],
                ["La justicia", "Justice"],
                ["La injusticia", "Injustice"],
                ["La libertad", "Freedom"],
                ["La lucha", "Struggle, fight"],
                ["El tribunal", "Court"],
                ["Abusar", "To abuse"],
                ["Aprobar (o→ue) una ley", "To pass a law"],
                ["Convocar", "To summon"],
                ["Defender (e→ie)", "To defend"],
                ["Derogar", "To abolish"],
                ["Encarcelar", "To imprison"],
                ["Juzgar", "To judge"],
                ["Analfabeto/a", "Illiterate"],
                ["Igual", "Equal"],
                ["Desigual", "Unequal"],
                ["Justo/a", "Fair"],
                ["Injusto/a", "Unfair"],
                ["Oprimido/a", "Oppressed"],
                ["La amenaza", "Threat"],
                ["El arma (f.)", "Weapon"],
                ["El escándalo", "Scandal"],
                ["La seguridad", "Security, safety"],
                ["La inseguridad", "Insecurity, lack of safety"],
                ["El temor", "Fear"],
                ["El terrorismo", "Terrorism"],
                ["La violencia", "Violence"],
                ["Chantajear", "To blackmail"],
                ["Destrozar", "To destroy"],
                ["Espiar", "To spy"],
                ["Huir", "To flee"],
                ["Pelear", "To fight"],
                ["Secuestrar", "To kidnap, to hijack"],
                ["El abuso", "Abuse"],
                ["La armada", "Navy"],
                ["La bandera", "Flag"],
                ["La creencia", "Belief"],
                ["La crueldad", "Cruelty"],
                ["La democracia", "Democracy"],
                ["La dictadura", "Dictatorship"],
                ["El ejército", "Army"],
                ["El gobierno", "Government"],
                ["La guerra (civil)", "(Civil) war"],
                ["El partido político", "Political party"],
                ["La paz", "Peace"],
                ["El poder", "Power"],
                ["La política", "Politics"],
                ["Las relaciones exteriores", "Foreign relations"],
                ["La victoria", "Victory"],
                ["Dedicar(se) a", "To devote oneself to"],
                ["Elegir (e→i)", "To elect"],
                ["Ganar las elecciones", "To win elections"],
                ["Perder (e→ie) las elecciones", "To lose elections"],
                ["Gobernar", "To govern"],
                ["Influir", "To influence"],
                ["Votar", "To vote"],
                ["Conservador", "Conservative (male)"],
                ["Conservadora", "Conservative (female)"],
                ["Liberal", "Liberal"],
                ["Pacífico", "Peaceful (male)"],
                ["Pacífica", "Peaceful (female)"],
                ["Pacifista", "Pacifist"],
                ["El abogado", "Lawyer (male)"],
                ["La abogada", "Lawyer (female)"],
                ["El activista", "Activist (male)"],
                ["La activista", "Activist (female)"],
                ["El ladrón", "Thief (male)"],
                ["La ladrona", "Thief (female)"],
                ["El manifestante", "Demonstrator (male)"],
                ["La manifestante", "Demonstrator (female)"],
                ["El político", "Politician (male)"],
                ["La política", "Politician (female)"],
                ["El presidente", "President (male)"],
                ["La presidenta", "President (female)"],
                ["El terrorista", "Terrorist (male)"],
                ["La terrorista", "Terrorist (female)"],
                ["La víctima", "Victim"],
                ["La acuarela", "Watercolor"],
                ["La caricatura", "Caricature"],
                ["La naturaleza", "Nature"],
                ["La naturaleza muerta", "Still-life"],
                ["Afuera", "Outside"],
                ["El retrato", "Portrait"],
                ["El autorretrato", "Self-portrait"],
                ["El paisaje", "Landscape"],
                ["Diseñar", "To design"],
                ["El diseño", "The design"],
                ["El arte de metamorfosis", "Metamorphic art"],
                ["El dibujo", "The drawing"],
                ["Dibujar", "To draw"],
                ["El mural", "The mural"],
                ["El arte religioso", "Religious art"],
                ["El cuadro, la pintura", "Painting"],
                ["La pintura al óleo", "Oil painting"],
                ["La mitología", "Mythology"],
                ["Mitológico/a", "Mythological"],
                ["El foco", "The focus"],
                ["Enfocarse en", "To focus on"],
                ["La imagen / Las imágenes", "The image(s)"],
                ["La meta", "The goal"],
                ["El objetivo", "The objective"],
                ["La muerte", "Death"],
                ["La cruz", "The cross"],
                ["La época", "The era"],
                ["El tema", "The topic, theme"],
                ["Tratar (de)", "To try / To deal with"],
                ["Los seres humanos", "Human beings"],
                ["El sujeto", "The subject"],
                ["Los cuerpos", "Bodies"],
                ["La textura", "Texture"],
                ["Los pasteles", "Pastels"],
                ["Brillante", "Bright"],
                ["Colorido/a", "Colorful"],
                ["Oscuro/a", "Dark"],
                ["Fuerte", "Strong"],
                ["Claro/a", "Light (color)"],
                ["Una mujer pálida", "A pale/fair woman"],
                ["Luz y sombras", "Light and shadows"],
                ["El espacio", "Space"],
                ["La semejanza", "Similarity"],
                ["La cara", "The face"],
                ["Las figuras", "The figures"],
                ["Moderno", "Modern"],
                ["Distinto / raro / extraño", "Different, strange"],
                ["Clásico", "Classical"],
                ["Los detalles", "The details"],
                ["El fondo", "Background"],
                ["El primer plano", "Foreground"],
                ["El sentimiento", "The feeling"],
                ["Conmocionar", "To move, affect deeply"],
                ["Redondo/a", "Round"],
                ["Audaz", "Bold"],
                ["La ilustración", "The illustration"],
                ["Ilustrar", "To illustrate"],
                ["Intentar", "To try"],
                ["Llevar a cabo", "To carry out, execute"],
                ["El patrón", "The sponsor, patron"],
                ["Patrocinar", "To sponsor"],
                ["Realizar", "To realize, execute, fulfill"],
                ["Sentirse orgulloso de", "To feel proud of"],
                ["La tristeza", "Sadness"],
                ["La exhibición de arte", "The art exhibit"],
                ["Una obra de arte", "A work of art"],
                ["Una obra maestra", "A masterpiece"],
                ["Antiguo/a", "Old, antique"],
                ["Contemporáneo/a", "Contemporary"],
                ["La línea", "The line"],
                ["Las pinceladas", "Brushstrokes"],
                ["Los pinceles", "Brushes"],
                ["La vida", "Life"],
                ["El cielo", "Sky / Heaven"],
            ]
        }
    },
    {
        id: "ap-espanol-tema-3",
        set: {
            title: "AP Español Lengua y Cultura — Tema 3 Vocabulario",
            vocab: [
                ["acreditado/a", "accredited"],
                ["ajeno/a", "foreign, belonging to someone else"],
                ["amalgamar", "to combine, to merge"],
                ["apartar", "to separate, to set aside"],
                ["atroz", "atrocious, terrible, cruel"],
                ["carecer de", "to lack, to be without"],
                ["conmover", "to move emotionally, to touch"],
                ["cotidiano/a", "daily, everyday"],
                ["deambular", "to wander, to stroll aimlessly"],
                ["despampanante", "stunning, of extraordinary beauty"],
                ["difundir", "to spread, to disseminate"],
                ["dispuesto/a", "prepared, ready"],
                ["el agrado / agradar / agradable", "pleasure, liking, to please, pleasant"],
                ["el alboroto", "commotion, disorder, tumult"],
                ["el capricho", "whim, impulse, arbitrary desire"],
                ["el convenio", "agreement, accord"],
                ["el denominador común", "common characteristic, common denominator"],
                ["el donaire", "grace, elegance, slenderness"],
                ["el guión", "script, plan, outline"],
                ["el hallazgo", "discovery, finding"],
                ["el juramento", "oath, vow"],
                ["el patrimonio", "heritage, inheritance"],
                ["el patrimonio artístico", "artistic heritage, national art collection"],
                ["el textil", "textile, woven fabric"],
                ["empeñarse en", "to insist on, to persist, to make an effort with determination"],
                ["encerrarse", "to shut oneself away, to isolate oneself"],
                ["fiable", "reliable, trustworthy"],
                ["hacer caso de", "to pay attention to, to heed"],
                ["ingresar", "to enter, to enroll in an institution"],
                ["insólito/a", "unusual, incredible, rare"],
                ["la casilla", "box, checkbox for marking a response"],
                ["la feria americana", "thrift sale, used clothing sale"],
                ["la mente", "mind, intellect, brain"],
                ["la prenda de vestir", "garment, article of clothing"],
                ["la privación", "deprivation, lack of basic goods"],
                ["la queja", "complaint, expression of displeasure"],
                ["menospreciar", "to despise, to look down on"],
                ["o sea", "that is to say, in other words"],
                ["presumir", "to show off, to boast"],
                ["profano/a", "secular, not religious or sacred"],
                ["proporcionar", "to provide, to supply, to offer"],
                ["radicar (en)", "to reside in, to consist of"],
                ["sensible", "sensitive, receptive"],
                ["un vistazo", "a quick glance, a brief look"],
                ["unirse", "to join, to unite with others"],
                ["vincular", "to link, to connect, to associate"]
            ]
        }
    },
    {
        id: "tema4-la-vida-contemporanea",
        set: {
            title: "Tema 4 - La vida contemporánea",
            vocab: [
                ["a condición de que", "provided that"],
                ["a fin de que", "so that, in order that"],
                ["adivinar", "to guess right"],
                ["ahorrar", "to save"],
                ["amargar", "to make bitter"],
                ["amarrar", "to tie"],
                ["analizar", "to analyze"],
                ["apostar", "to bet"],
                ["asar", "to roast, to barbecue"],
                ["aunque", "even though, even if"],
                ["batir", "to beat"],
                ["bucear", "to scuba dive"],
                ["cazar", "to hunt"],
                ["cocer", "to boil"],
                ["colar", "to strain"],
                ["conseguir", "to get"],
                ["dar una caminata", "to hike"],
                ["darse por vencido", "to give up"],
                ["dentro de poco", "shortly, in a short while"],
                ["echar", "to pour"],
                ["el abogado", "lawyer"],
                ["el aficionado", "fan"],
                ["el arquitécto", "architect"],
                ["el boliche", "bowling"],
                ["el carné", "ID"],
                ["el día feriado", "holiday"],
                ["el ecoturismo", "ecotourism"],
                ["el empresario", "business man"],
                ["el entretenimiento", "entertainment"],
                ["el espectáculo", "show"],
                ["el gerente", "manager"],
                ["el grano", "grain"],
                ["el ingeniero", "engineer"],
                ["el jefe", "boss"],
                ["el juez", "judge"],
                ["el médico", "doctor"],
                ["el medioambiente", "environment"],
                ["el pavo", "turkey"],
                ["el puente", "bridge"],
                ["el zoológico", "zoo"],
                ["el/la periodista", "journalist"],
                ["el/la policía", "police officer"],
                ["el/la sartén", "pan"],
                ["emocionante", "exciting"],
                ["en resumen", "in summary"],
                ["enriquecer", "to enrich"],
                ["esforzarse", "to make an effort"],
                ["extrañar", "to miss someone"],
                ["gastar", "to spend"],
                ["gozar", "to enjoy"],
                ["hace poco", "a short while ago"],
                ["hornear", "to bake"],
                ["impresionante", "impressive"],
                ["la bahía", "bay"],
                ["la carretera", "highway"],
                ["la catarata", "waterfall"],
                ["la cazuela", "casserole dish"],
                ["la cucharada", "table spoon"],
                ["la cucharadita", "tea spoon"],
                ["la discoteca", "disco, dance club"],
                ["la diversión", "fun"],
                ["la fogata", "campfire"],
                ["la frontera", "border"],
                ["la montaña rusa", "roller coaster"],
                ["la nuez", "walnut"],
                ["la receta", "recipe"],
                ["la semilla", "seed"],
                ["las especias", "spices"],
                ["licuar", "to blend"],
                ["los naipes", "playing cards"],
                ["mezclar", "to mix"],
                ["pescar", "to fish"],
                ["platicar", "to chat"],
                ["rebanar", "to slice"],
                ["recreativo", "recreational"],
                ["rellenar", "to fill"],
                ["sazonar", "to season"],
                ["trasnochar", "to stay up late"]
            ]
        }
    },
    {
        id: "ap-esp-tenses-1",
        set: {
            "title": "Secuencia de Tiempos: Práctica Extendida (40 Más)",
            "vocab": [
                ["Ojalá que tú ___ el documento a tiempo. (enviar)", "hubieras enviado"],
                ["Me molestó que ellos no ___ la mesa. (poner)", "pusieran"],
                ["Era increíble que tú ___ tan bien. (pintar)", "pintaras"],
                ["Esperaba que ustedes ___ el plan. (seguir)", "siguieran"],
                ["Ojalá que él ___ el error antes. (notar)", "hubiera notado"],
                ["Me alegró que tú ___ la invitación. (aceptar)", "aceptaras"],
                ["Era raro que ellos no ___ la reunión. (recordar)", "recordaran"],
                ["No pensábamos que tú ___ tan lejos. (caminar)", "caminaras"],
                ["Ojalá que nosotros ___ el dinero. (encontrar)", "hubiéramos encontrado"],
                ["Me sorprendió que ella ___ tan rápido. (responder)", "respondiera"],
                ["Era necesario que tú ___ la luz. (apagar)", "apagaras"],
                ["No querían que nosotros ___ tarde. (salir)", "saliéramos"],
                ["Ojalá que ustedes ___ el archivo. (descargar)", "hubieran descargado"],
                ["Me encantó que tú ___ con nosotros. (viajar)", "viajaras"],
                ["Era lógico que ellos ___ nerviosos. (estar)", "estuvieran"],
                ["Esperaba que tú ___ el paquete. (recoger)", "recogieras"],
                ["Ojalá que él ___ la puerta. (cerrar)", "hubiera cerrado"],
                ["Me molestaba que tú no ___ el consejo. (seguir)", "siguieras"],
                ["Era triste que ellos no ___ la oportunidad. (ver)", "vieran"],
                ["Ojalá que nosotros ___ más temprano. (llegar)", "hubiéramos llegado"],
                ["Me alegró que tú ___ la comida. (probar)", "probaras"],
                ["No creían que ella ___ tan rápido. (leer)", "leyera"],
                ["Era posible que ellos ___ la solución. (encontrar)", "encontraran"],
                ["Ojalá que tú ___ el problema. (entender)", "hubieras entendido"],
                ["Me sorprendió que ustedes ___ tan bien. (cocinar)", "cocinaran"],
                ["Era importante que tú ___ la cita. (confirmar)", "confirmaras"],
                ["No querían que nosotros ___ solos. (andar)", "andáramos"],
                ["Ojalá que ellos ___ el correo. (abrir)", "hubieran abierto"],
                ["Me encantó que tú ___ conmigo. (estudiar)", "estudiaras"],
                ["Era raro que él no ___ la noticia. (saber)", "supiera"],
                ["Esperaba que tú ___ el informe. (leer)", "leyeras"],
                ["Ojalá que ustedes ___ el proyecto. (terminar)", "hubieran terminado"],
                ["Me molestaba que ellos no ___ el cuarto. (limpiar)", "limpiaran"],
                ["Era lógico que tú ___ confundido. (estar)", "estuvieras"],
                ["Ojalá que nosotros ___ más energía. (tener)", "hubiéramos tenido"],
                ["Me alegró que tú ___ la decisión. (tomar)", "tomaras"],
                ["No pensábamos que ella ___ tan bien. (cantar)", "cantara"],
                ["El profesor quería que nosotros ___ la actividad. (completar)", "completáramos"],
                ["Ojalá que tú ___ la llamada. (contestar)", "hubieras contestado"],
                ["Me sorprendió que ellos ___ tan rápido. (avanzar)", "avanzaran"],
                ["Ojalá que tú ___ la verdad antes. (descubrir)", "hubieras descubierto"],
                ["Me molestó que ustedes no ___ a tiempo. (llegar)", "llegaran"],
                ["Era increíble que él ___ todo solo. (organizar)", "organizara"],
                ["Esperaba que tú ___ el documento final. (revisar)", "revisaras"],
                ["Ojalá que ellos ___ la situación. (comprender)", "hubieran comprendido"],
                ["Me alegró que tú ___ la presentación. (preparar)", "prepararas"],
                ["Era raro que nosotros no ___ el ruido. (oír)", "oyéramos"],
                ["No pensábamos que tú ___ tan bien. (escribir)", "escribieras"],
                ["Ojalá que ella ___ la verdad. (admitir)", "hubiera admitido"],
                ["Me sorprendió que ustedes ___ tan tarde. (despertarse)", "se despertaran"],
                ["Era necesario que él ___ la lista. (hacer)", "hiciera"],
                ["No querían que tú ___ solo. (salir)", "salieras"],
                ["Ojalá que nosotros ___ el error. (corregir)", "hubiéramos corregido"],
                ["Me encantó que tú ___ la historia. (contar)", "contaras"],
                ["Era lógico que ellos ___ confundidos. (sentirse)", "se sintieran"],
                ["Esperaba que tú ___ la caja. (abrir)", "abrieras"],
                ["Ojalá que él ___ el examen. (aprobar)", "hubiera aprobado"],
                ["Me molestaba que tú no ___ la mesa. (poner)", "pusieras"],
                ["Era triste que ellos no ___ el viaje. (disfrutar)", "disfrutaran"],
                ["Ojalá que nosotros ___ más tiempo libre. (tener)", "hubiéramos tenido"],
                ["Me alegró que tú ___ la verdad. (decir)", "dijeras"],
                ["No creían que ella ___ tan rápido. (correr)", "corriera"],
                ["Era posible que ellos ___ la respuesta correcta. (dar)", "dieran"],
                ["Ojalá que tú ___ la oportunidad. (aprovechar)", "hubieras aprovechado"],
                ["Me sorprendió que ustedes ___ tan bien. (actuar)", "actuaran"],
                ["Era importante que tú ___ la puerta. (cerrar)", "cerraras"],
                ["No querían que nosotros ___ tarde. (volver)", "volviéramos"],
                ["Ojalá que ellos ___ el paquete. (recibir)", "hubieran recibido"],
                ["Me encantó que tú ___ conmigo. (caminar)", "caminaras"],
                ["Era raro que él no ___ la música. (escuchar)", "escuchara"],
                ["Esperaba que tú ___ la comida. (calentar)", "calentaras"],
                ["Ojalá que ustedes ___ la reunión. (recordar)", "hubieran recordado"],
                ["Me molestaba que ellos no ___ el proyecto. (empezar)", "empezaran"],
                ["Era lógico que tú ___ nervioso. (ponerse)", "te pusieras"],
                ["Ojalá que nosotros ___ el documento. (guardar)", "hubiéramos guardado"],
                ["Me alegró que tú ___ la idea. (proponer)", "propusieras"],
                ["No pensábamos que ella ___ tan alto. (saltar)", "saltara"],
                ["El profesor quería que nosotros ___ más. (practicar)", "practicáramos"],
                ["Ojalá que tú ___ la nota. (escribir)", "hubieras escrito"],
                ["Me sorprendió que ellos ___ tan bien. (dibujar)", "dibujaran"],
                ["Ojalá que tú ___ el libro correcto. (escoger)", "hubieras escogido"],
                ["Me molestó que ellos no ___ la cita. (confirmar)", "confirmaran"],
                ["Era increíble que tú ___ tan rápido. (aprender)", "aprendieras"],
                ["Esperaba que ustedes ___ la mesa. (limpiar)", "limpiaran"],
                ["Ojalá que él ___ la verdad. (revelar)", "hubiera revelado"],
                ["Me alegró que tú ___ la caja. (cerrar)", "cerraras"],
                ["Era raro que ellos no ___ la señal. (ver)", "vieran"],
                ["No pensábamos que tú ___ tan bien. (cocinar)", "cocinaras"],
                ["Ojalá que nosotros ___ el archivo. (abrir)", "hubiéramos abierto"],
                ["Me sorprendió que ella ___ tan amable. (ser)", "fuera"],
                ["Era necesario que tú ___ el papel. (firmar)", "firmaras"],
                ["No querían que nosotros ___ solos. (esperar)", "esperáramos"],
                ["Ojalá que ustedes ___ la tarea. (entregar)", "hubieran entregado"],
                ["Me encantó que tú ___ conmigo. (practicar)", "practicaras"],
                ["Era lógico que ellos ___ cansados. (estar)", "estuvieran"],
                ["Esperaba que tú ___ la ropa. (doblar)", "doblaras"],
                ["Ojalá que él ___ el problema. (resolver)", "hubiera resuelto"],
                ["Me molestaba que tú no ___ el libro. (traer)", "trajeras"],
                ["Era triste que ellos no ___ el evento. (asistir)", "asistieran"],
                ["Ojalá que nosotros ___ la comida. (comprar)", "hubiéramos comprado"],
                ["Me alegró que tú ___ el examen. (pasar)", "pasaras"],
                ["No creían que ella ___ tan bien. (bailar)", "bailara"],
                ["Era posible que ellos ___ la caja. (mover)", "movieran"],
                ["Ojalá que tú ___ el error. (notar)", "hubieras notado"],
                ["Me sorprendió que ustedes ___ tan rápido. (terminar)", "terminaran"],
                ["Era importante que tú ___ la computadora. (apagar)", "apagaras"],
                ["No querían que nosotros ___ tarde. (despertarse)", "nos despertáramos"],
                ["Ojalá que ellos ___ la puerta. (cerrar)", "hubieran cerrado"],
                ["Me encantó que tú ___ conmigo. (hablar)", "hablaras"],
                ["Era raro que él no ___ la instrucción. (seguir)", "siguiera"],
                ["Esperaba que tú ___ el correo. (leer)", "leyeras"],
                ["Ojalá que ustedes ___ el viaje. (planear)", "hubieran planeado"],
                ["Me molestaba que ellos no ___ la lámpara. (encender)", "encendieran"],
                ["Era lógico que tú ___ confundido. (sentirse)", "te sintieras"],
                ["Ojalá que nosotros ___ más agua. (beber)", "hubiéramos bebido"],
                ["Me alegró que tú ___ la caja. (levantar)", "levantaras"],
                ["No pensábamos que ella ___ tan bien. (tocar)", "tocara"],
                ["El profesor quería que nosotros ___ la lectura. (analizar)", "analizáramos"],
                ["Ojalá que tú ___ la llave. (encontrar)", "hubieras encontrado"],
                ["Me sorprendió que ellos ___ tan lejos. (viajar)", "viajaran"],
                ["Ojalá que tú ___ la puerta con llave. (cerrar)", "hubieras cerrado"],
                ["Me molestó que ellos no ___ el informe. (leer)", "leyeran"],
                ["Era increíble que tú ___ tan fuerte. (gritar)", "gritaras"],
                ["Esperaba que ustedes ___ la actividad. (organizar)", "organizaran"],
                ["Ojalá que él ___ la comida. (probar)", "hubiera probado"],
                ["Me alegró que tú ___ la caja. (abrir)", "abrieras"],
                ["Era raro que ellos no ___ la señal. (seguir)", "siguieran"],
                ["No pensábamos que tú ___ tan bien. (nadar)", "nadaras"],
                ["Ojalá que nosotros ___ el problema. (entender)", "hubiéramos entendido"],
                ["Me sorprendió que ella ___ tan rápido. (escribir)", "escribiera"],
                ["Era necesario que tú ___ la mochila. (traer)", "trajeras"],
                ["No querían que nosotros ___ solos. (caminar)", "camináramos"],
                ["Ojalá que ustedes ___ el documento. (firmar)", "hubieran firmado"],
                ["Me encantó que tú ___ conmigo. (colaborar)", "colaboraras"],
                ["Era lógico que ellos ___ preocupados. (estar)", "estuvieran"],
                ["Esperaba que tú ___ el proyecto. (empezar)", "empezaras"],
                ["Ojalá que él ___ la ventana. (abrir)", "hubiera abierto"],
                ["Me molestaba que tú no ___ la verdad. (admitir)", "admitieras"]
            ]
        }

    },
    {
        "id": "biotech-2-final-1",
        "set": {
            "title": "Biotechnology 2 – Semester 1 Final Exam Flashcards (With Real-Life Lab Examples)",
            "vocab": [
                ["Proper disposal of chemical waste", "Dispose only in designated chemical waste containers per SDS. Example: Used acetone goes in the flammable waste container, not the sink."],
                ["Proper disposal of biological waste", "Place contaminated materials in biohazard bags. Example: Pipette tips used with bacteria go into a red biohazard container."],
                ["First response to hazardous chemical spill", "Alert others and notify the instructor. Example: If bleach spills, step back, warn classmates, and wait for instructions."],
                ["Biosafety level for smallpox virus", "BSL-4—maximum containment."],
                ["OSHA", "Agency that regulates workplace safety."],
                ["Hazardous Communications System (HCS)", "Ensures workers know chemical hazards via labels/SDS/training."],
                ["Preventative & responsive safety equipment", "Equipment used before or during accidents. Example: Fire extinguisher for flames; lab coat to prevent chemical contact."],
                ["Not standard safety equipment", "Items not allowed in labs. Example: A student wearing sandals or AirPods is violating lab safety."],
                ["Equipment not recommended in labs", "Items like mercury thermometers or loose jewelry that can cause contamination or breakage."],
                ["Primary source of chemical info", "Safety Data Sheet (SDS)."],
                ["SDS disposal section", "Section 13: Disposal Considerations."],
                ["Universal labeling requirement", "Every container must show contents and hazards. Example: Even water in a beaker must be labeled 'water'."],
                ["Where chemicals should never be stored", "On the floor, near heat, or in sunlight. Example: Placing acids on the windowsill is unsafe."],
                ["First step for spill response", "Assess safety & notify instructor before cleaning."],
                ["Example of biological spill", "Dropping a tube of E. coli culture on the floor."],
                ["Example of chemical spill", "Knocking over a bottle of hydrochloric acid."],
                ["First-aid for acid on skin", "Rinse under water for 15+ minutes immediately."],
                ["Required waste container info", "Contents, hazards, date, and responsible person."],
                ["Biological waste classification", "Biohazard; requires special containment and disposal."],
                ["When responsive safety equipment is used", "Emergencies. Example: Eyewash used when a student gets buffer splash in eyes."],
                ["Equipment Usage Log components", "User, date/time, purpose, and parameters used."],
                ["Equipment Maintenance Log components", "Repairs, calibration, inspections, service dates."],
                ["Acid never mixed with others", "Perchloric acid—extremely reactive."],
                ["Operational techniques definition", "Quality practices ensuring consistent product/service."],
                ["Container for solid non-sharp bio waste", "Biohazard autoclave bag in rigid bin."],
                ["Why FDA requires a Quality System", "Ensures safety, consistency, and compliance in biotech manufacturing."],
                ["Primary role of QA", "Oversees documentation, compliance, audits, and product quality."],
                ["Committee reviewing hazardous agent research", "Institutional Biosafety Committee (IBC)."],
                ["IACUC", "Committee overseeing vertebrate animal research."],
                ["Legal consequence of not warning pregnant women", "Liability, lawsuits, ethical violations."],
                ["HIPAA", "Protects patient medical privacy."],
                ["Children as research population", "Considered a vulnerable population requiring extra protections."],
                ["Ethics vs. legality", "Something can be legal but unethical, or ethical but restricted by law."],
                ["Bioethical issues", "Controversial topics like stem cells, cloning, gene editing, privacy, animal use."],
                ["Posting patient info violation", "HIPAA violation."],
                ["Unauthorized release term", "Data breach."],
                ["Intellectual property", "Legal protection for original creations/inventions."],
                ["Government-funded IP complexity", "Ownership may be shared or regulated by laws (e.g., Bayh-Dole)."],
                ["Strong research question characteristics", "Clear, testable, specific, measurable."],
                ["Evaluating source reliability", "Check bias, accuracy, recency, and credibility."],
                ["Negative control in insulin PCR", "Reaction with no DNA template (water)."],
                ["Importance of reproducible procedures", "Allows replication and verification by others."],
                ["Proper aseptic techniques", "Flaming loop, not leaving plates open, streaking correctly."],
                ["Improper aseptic techniques", "Touching agar with fingers, leaving plates open, re-crossing streak quadrants."],
                ["Strong scientific conclusion", "Uses data, states results clearly, explains errors, ties back to hypothesis."],
                ["Primary structure of protein", "Sequence of amino acids."],
                ["Why prokaryotes are used", "Grow fast, cheap, easy to manipulate genetically."],
                ["Elution in chromatography", "Removing bound molecules from a column with buffer."],
                ["Hydrophobic proteins", "Water-repelling; nonpolar regions."],
                ["Hydrophilic proteins", "Water-attracting; polar regions."],
                ["What chromatography separates", "Molecules based on size, charge, affinity, hydrophobicity."],
                ["Why antibodies are specific", "Their binding sites match only one antigen shape."],
                ["Purpose of plate-based ELISA", "Detects and quantifies proteins/antigens in many samples at once."],
                ["BLAST", "Tool that compares DNA/protein sequences to known sequences."],
                ["Where to run BLAST", "NCBI database website."],
                ["Example of unsafe lab outfit", "A student wearing shorts, sandals, no goggles, and a loose hoodie—unsafe due to exposed skin, tripping hazards, and lack of PPE."],
                ["Example of safe lab outfit", "Closed-toe shoes, long pants, tied-back hair, goggles, gloves, and a lab coat."]
            ]
        }
    }




]
