import { title } from "process";
import { AllSetsInterface } from "../AllSets";


export const SIXA: AllSetsInterface = {
    id: "esp-vocab-6a-mi-casa-es-su-casa",
    set: {
        title: "Vocabulario Unidad 6A: Mi casa es su casa",
        vocab: [
            ["El refrigerador", "refrigerator"],
            ["Los cubiertos", "silverware; utensils"],
            ["La estufa", "stove"],
            ["El fregadero", "sink"],
            ["El horno microondas", "microwave oven"],
            ["El lavaplatos", "dishwasher"],
            ["Los platos especiales", "special dishes"],
            ["Los platos de todos los días", "everyday dishes"],
            ["Las servilletas", "napkins"],
            ["Los vasos", "glasses"],
            ["La luz / las luces", "light / lights"],
            ["La lámpara", "lamp"],
            ["La mesa", "table"],
            ["El comedor", "dining room"],
            ["La cena", "dinner"],
            ["Tener", "to have"],
            ["Tener que", "to have to"],
            ["Querer", "to want; to love"],
            ["Empezar", "to begin"],
            ["Deber", "must; to have a duty or obligation"],
            ["Ayudar", "to help"],
            ["Cerrar", "to close"],
            ["Comenzar", "to begin"],
            ["Encender", "to turn on"],
            ["Preferir", "to prefer"],
            ["Sentir", "to feel; to regret"],
            ["Poner la mesa", "to set the table"],
            ["El mantel", "tablecloth"],
            ["La cucharita", "teaspoon"],
            ["La cuchara", "spoon"],
            ["El cuchillo", "knife"],
            ["El tenedor", "fork"],
            ["El aceite", "oil"],
            ["La sal", "salt"],
            ["La pimienta", "pepper"],
            ["La taza", "cup"],
            ["El azúcar", "sugar"],
            ["El pan", "bread"],
            ["La mantequilla", "butter"],
            ["La sopa", "soup"],
            ["La mayonesa", "mayonnaise"],
            ["La mostaza", "mustard"],
            ["La salsa de tomate", "ketchup"],
            ["El postre", "dessert"],
            ["Pásame", "pass me"],
            ["Dulce", "sweet"],
            ["Allá", "over there"],
            ["Picante", "spicy"],
            ["El sabor", "flavor; taste"],
            ["Sabroso/a", "tasty"],
            ["Delicioso/a", "delicious"],
            ["Salado/a", "salty"],
            ["También", "also"],
            ["Agrio/a", "sour"],
            ["Desayuno", "breakfast"],
            ["Pensar", "to think"],
            ["Almuerzo", "lunch"],
            ["Venir", "to come"]

        ]
    }
}

export const SIXB: AllSetsInterface = {
    id: "esp-vocab-6b-mi-casa-es-su-casa",
    set: {
        title: "Vocabulario Unidad 6B: Mi casa es su casa",
        vocab: [

            ["La planta baja", "Downstairs"],
            ["Una casa de dos pisos", "A two-story house"],
            ["El teléfono", "The telephone"],
            ["El garaje", "The garage"],
            ["La cochera", "The garage / carport"],
            ["La sala", "The living room"],
            ["La piscina", "The pool"],
            ["La escalera", "The stairs"],
            ["El cuarto", "The room / bedroom"],
            ["El baño", "The bathroom"],
            ["El patio", "The patio / backyard"],
            ["La cocina", "The kitchen"],
            ["Las plantas", "The plants"],
            ["El dibujo", "The drawing"],
            ["Pequeño", "Small"],
            ["Grande", "Big / large"],
            ["Abrazo", "Hug"],
            ["Cómodo", "Comfortable"],
            ["Querido", "Dear"],
            ["Aprender", "To learn"],
            ["Al lado de", "Next to / beside"],
            ["Por la noche", "At night"],
            ["Tengo ganas de", "I feel like / I have feelings to"],
            ["Carta", "Letter"],
            ["Tener calor", "To be hot"],
            ["Tener frío", "To be cold"],
            ["Tener sed", "To be thirsty"],
            ["Tener hambre", "To be hungry"],
            ["Tener miedo", "To be afraid"],
            ["Estar cansado", "To be tired"],
            ["Tener sueño", "To be sleepy"],
            ["Cantar", "To sing"],
            ["Tocar música", "To play music"],
            ["Correr", "To run"],
            ["Pedir prestado", "To borrow"],
            ["Pedir permiso", "To ask for permission"],
            ["Decir la verdad", "To tell the truth"],
            ["Devolver", "To return (to give back)"],
            ["Engañar", "To cheat"],
            ["Pedir disculpas", "To apologize"],
            ["Pedir perdón", "To ask for forgiveness"],
            ["Ser honesto", "To be honest"],
            ["Tener cuidado", "To be careful"],
            ["Tener razón", "To be right"],
            ["Tener prisa", "To be in a hurry"]

        ]

    }
}

export const FiveA: AllSetsInterface = {
    id: "esp-vocab-5a-la-rutina-y-la-diversion",
    set: {
        title: "Vocabulario Unidad 5A: La rutina y la diversión",
        vocab: [
            ["la práctica (de)", "the practice"],
            ["la librería", "bookstore"],
            ["la bicicleta", "the bicycle"],
            ["(hacer) la maleta", "to pack / to make a suitcase"],
            ["(hacer) un viaje", "to take a trip"],
            ["abrir", "to open"],
            ["buscar", "to look for"],
            ["entrar", "to enter"],
            ["llamar", "to call"],
            ["llevar", "to take"],
            ["montar", "to ride"],
            ["pasar tiempo", "to spend time"],
            ["tener", "to have"],
            ["ver", "to see / to watch"],
            ["escuchar", "to listen"],
            ["viajar", "to travel"],
            ["conocer", "to know (to be familiar with)"],
            ["disfrutar", "to enjoy"],
            ["explorar", "to explore"],
            ["descargar música", "to download music"],
            ["el amor", "love"],
            ["cada", "every / each"],
            ["la canción", "the song"],
            ["¡caramba!", "wow!"],
            ["el/la compañero/a", "partner / classmate"],
            ["el fin de semana", "weekend"],
            ["¡qué + adj/noun!", "what a... / how..."],
            ["la semana", "week"],
            ["la sorpresa", "the surprise"],
            ["todos los días", "every day"],
            ["antes", "before"],
            ["durante", "during"],
            ["después", "after"],
            ["el próximo fin de semana", "next weekend"],
            ["abierto/a", "open"],
            ["cerrado/a", "closed"]
        ]
    }

}

export const FiveB: AllSetsInterface = {
    id: "esp-vocab-5b-la-rutina-y-la-diversion",
    set: {
        title: "Vocabulario Unidad 5B: La rutina y la diversión",
        vocab: [
            ["El cumpleaños", "Birthday"],
            ["La Navidad", "Christmas"],
            ["Año Nuevo", "New Year"],
            ["Mayor", "Older"],
            ["Menor", "Younger"],
            ["Primero", "First"],
            ["Ayer", "Yesterday"],
            ["Anteayer", "The day before yesterday"],
            ["Mañana", "Tomorrow"],
            ["Pasado mañana", "The day after tomorrow"],
            ["Hoy", "Today"],
            ["Enero", "January"],
            ["Febrero", "February"],
            ["Marzo", "March"],
            ["Abril", "April"],
            ["Mayo", "May"],
            ["Junio", "June"],
            ["Julio", "July"],
            ["Agosto", "August"],
            ["Septiembre", "September"],
            ["Octubre", "October"],
            ["Noviembre", "November"],
            ["Diciembre", "December"],
            ["Celebrar", "To celebrate"],
            ["Cumplir años", "To turn years old"]
        ]
    }

}


export const SevenA: AllSetsInterface = {
    id: "esp-vocab-7a-los-pasatiempos",
    set: {
        title: "Vocabulario Unidad 7A: Los pasatiempos",
        vocab: [

            ["El pasatiempo", "Hobby"],
            ["El ajedrez", "Chess"],
            ["El básquetbol", "Basketball"],
            ["Las cartas", "Cards"],
            ["Las damas", "Checkers"],
            ["El equipo", "Team"],
            ["El fútbol americano", "Football"],
            ["El voleibol", "Volleyball"],
            ["El aficionado(a)", "Fan"],
            ["El programa", "TV show"],
            ["Alquilar", "To rent"],
            ["Apagar", "To turn off"],
            ["Costar (o-ue)", "To cost/price"],
            ["Dibujar", "To draw"],
            ["Dormir (o-ue)", "To sleep"],
            ["Jugar (u-ue)", "To play"],
            ["Permitir", "To allow"],
            ["Poder (o-ue)", "To be able to"],
            ["Recordar (o-ue)", "To remember"],
            ["Volver (o-ue)", "To come back"],
            ["Ganar", "To win"],
            ["Perder (e-ie)", "To lose"],
            ["Pintar", "To draw"],
            ["Subir", "To go up"],
            ["Descansar", "To rest"]

        ]
    }

}


export const SevenB: AllSetsInterface = {
    id: "esp-vocab-7b-los-pasatiempos",
    set: {
        title: "Vocabulario Unidad 7A: Los pasatiempos",
        vocab: [

            ["Está nublado / hay nubes", "It’s cloudy"],
            ["Está soleado / hace sol", "It’s sunny"],
            ["Hace calor", "It’s hot"],
            ["Hace fresco", "It’s cool"],
            ["Hace frío", "It’s cold"],
            ["Las estaciones", "Seasons"],
            ["El invierno", "Winter"],
            ["La primavera", "Spring"],
            ["El otoño", "Fall"],
            ["El verano", "Summer"],
            ["El hielo", "Ice"],
            ["La nieve", "Snow"],
            ["La lluvia", "Rain"],
            ["Hace viento", "It’s windy"],
            ["Hay neblina", "There is fog"],
            ["Hace buen tiempo", "It’s good weather"],
            ["Hace mal tiempo", "It’s bad weather"],
            ["Temperatura máxima", "Maximum temperature"],
            ["Temperatura mínima", "Minimum temperature"],
            ["Grados", "Degrees"],
            ["Dar un paseo por la playa", "To walk on the beach"],
            ["Montar en patineta", "To skateboard"],
            ["Patinar sobre hielo", "To ice skate"],
            ["Enviar", "To send"],
            ["Copiar", "To copy"],
            ["Esquiar", "To ski"],
            ["Continuar", "To continue"],
            ["Estudiar", "To study"],
            ["Poner", "To put/to place"],
            ["Saber", "To know (facts)"],
            ["Ver", "To see"],
            ["Salir", "To exit"],
            ["Dar", "To give"],
            ["Nevar", "To snow"],
            ["Llover", "To rain"],
            ["El corredor / la corredora", "The runner"],
            ["El/la futbolista / el jugador de fútbol", "The soccer player"],
            ["El esquiador / la esquiadora", "The skier"],
            ["El patinador / la patinadora", "The ice skater"],
            ["El jugador / la jugadora", "The player"],
            ["El/la basquetbolista", "The basketball player"],
            ["El/la tenista", "The tennis player"],
            ["El/la deportista", "The athlete"],
            ["Primero / Primera (1º/1ª)", "First"],
            ["Segundo / Segunda (2º/2ª)", "Second"],
            ["Tercero / Tercera (3º/3ª)", "Third"],
            ["Cuarto / Cuarta (4º/4ª)", "Fourth"],
            ["Quinto / Quinta (5º/5ª)", "Fifth"],
            ["Sexto / Sexta (6º/6ª)", "Sixth"],
            ["Séptimo / Séptima (7º/7ª)", "Seventh"],
            ["Octavo / Octava (8º/8ª)", "Eighth"],
            ["Noveno / Novena (9º/9ª)", "Ninth"],
            ["Décimo / Décima (10º/10ª)", "Tenth"],
            ["Me encanta", "I love"],
            ["Los patines", "The skates"],
            ["El sitio", "The place"],
            ["El aire libre", "The outdoors"],
            ["Por todas partes", "Everywhere"]

        ]
    }

}

const Unidad1: AllSetsInterface[] = [
    {
        "id": "esp-vocab-1a",
        "set": {
            "title": "Vocabulario Unidad 1A: El Comienzo",
            "vocab": [
                ["¡Hola!", "Hello!"],
                ["¿Cómo te llamas?", "What is your name?"],
                ["Yo me llamo", "My name is"],
                ["¿Y tú?", "And you?"],
                ["Mucho gusto", "Nice to meet you"],
                ["Adiós", "Goodbye"],
                ["Hasta luego", "See you later"],
                ["Nos vemos", "See you"],
                ["¿Cómo se escribe ___?", "How do you spell ___?"],
                ["Se escribe con ___", "It is spelled with ___"],
                ["Acento", "Accent mark"],
                ["Mayúscula", "Capital letter"],
                ["Minúscula", "Lowercase letter"],
                ["Gracias", "Thank you"],
                ["De nada", "You're welcome"],
                ["¿Puedo ir al baño?", "Can I go to the bathroom?"],
                ["Salud", "Bless you"],
                ["¿Puedo tomar agua?", "Can I drink water?"],
                ["¿De dónde eres?", "Where are you from?"],
                ["Soy de", "I am from"],
                ["¿Eres de aquí?", "Are you from here?"],
                ["¿Cuántos años tienes?", "How old are you?"],
                ["Tengo ___ años", "I am ___ years old"],
                ["Cero", "Zero"],
                ["Uno", "One"],
                ["Dos", "Two"],
                ["Tres", "Three"],
                ["Cuatro", "Four"],
                ["Cinco", "Five"],
                ["Seis", "Six"],
                ["Siete", "Seven"],
                ["Ocho", "Eight"],
                ["Nueve", "Nine"],
                ["Diez", "Ten"],
                ["Once", "Eleven"],
                ["Doce", "Twelve"],
                ["Trece", "Thirteen"],
                ["Catorce", "Fourteen"],
                ["Quince", "Fifteen"],
                ["Dieciséis", "Sixteen"],
                ["Diecisiete", "Seventeen"],
                ["Dieciocho", "Eighteen"],
                ["Diecinueve", "Nineteen"],
                ["Veinte", "Twenty"]
            ]
        }
    },
    {
        "id": "esp-vocab-1b",
        "set": {
            "title": "Vocabulario Unidad 1B: El Comienzo",
            "vocab": [
                ["Buenos días", "Good morning"],
                ["Buenas tardes", "Good afternoon"],
                ["Buenas noches", "Good evening / Good night"],
                ["¿Cómo está usted, señora?", "How are you, ma’am?"],
                ["Estoy bien, gracias", "I am fine, thank you"],
                ["¿Cómo estás?", "How are you? (informal)"],
                ["¿Cómo está ella/él?", "How is she/he?"],
                ["¿Y él/ella/ustedes?", "And he/she/you all?"],
                ["¿Qué tal?", "How’s it going?"],
                ["Muy bien", "Very well"],
                ["Estoy regular", "I’m so-so"],
                ["Más o menos", "More or less"],
                ["Señorita (Srta.)", "Miss"],
                ["Señora (Sra.)", "Mrs."],
                ["Señor (Sr.)", "Mr."],
                ["Hasta mañana", "See you tomorrow"],
                ["Hasta pronto", "See you soon"],
                ["Con permiso, por favor", "Excuse me, please"],
                ["¡Con mucho gusto!", "With pleasure! / You’re welcome!"],
                ["¿Qué hora es?", "What time is it?"],
                ["Es la una y media", "It is one thirty"],
                ["Estoy mal", "I am not well"],
                ["Lo siento", "I’m sorry"],
                ["Muchas gracias", "Thank you very much"],
                ["De nada", "You’re welcome"],
                ["Perdón", "Excuse me / Sorry"],
                ["Son las… (plural)", "It is… (plural hour)"],
                ["Es la… (singular)", "It is… (singular hour)"],
                ["De la mañana", "In the morning"],
                ["De la tarde", "In the afternoon"],
                ["De la noche", "At night"],
                ["Uno", "One"],
                ["Dos", "Two"],
                ["Tres", "Three"],
                ["Cuatro", "Four"],
                ["Cinco", "Five"],
                ["Seis", "Six"],
                ["Siete", "Seven"],
                ["Ocho", "Eight"],
                ["Nueve", "Nine"],
                ["Diez", "Ten"],
                ["Once", "Eleven"],
                ["Doce", "Twelve"],
                ["Trece", "Thirteen"],
                ["Catorce", "Fourteen"],
                ["Quince", "Fifteen"],
                ["Cuarto (15)", "Quarter (15 minutes)"],
                ["Dieciséis", "Sixteen"],
                ["Diecisiete", "Seventeen"],
                ["Dieciocho", "Eighteen"],
                ["Diecinueve", "Nineteen"],
                ["Veinte", "Twenty"],
                ["Veintiuno", "Twenty-one"],
                ["Veintidós", "Twenty-two"],
                ["Veintitrés", "Twenty-three"],
                ["Veinticuatro", "Twenty-four"],
                ["Veinticinco", "Twenty-five"],
                ["Veintiséis", "Twenty-six"],
                ["Veintisiete", "Twenty-seven"],
                ["Veintiocho", "Twenty-eight"],
                ["Veintinueve", "Twenty-nine"],
                ["Treinta", "Thirty"],
                ["Treinta y uno", "Thirty-one"],
                ["Treinta y dos", "Thirty-two"],
                ["Cuarenta", "Forty"],
                ["Cuarenta y uno", "Forty-one"],
                ["Cincuenta", "Fifty"],
                ["Sesenta", "Sixty"],
                ["Setenta", "Seventy"],
                ["Ochenta", "Eighty"],
                ["Noventa", "Ninety"],
                ["Cien", "One hundred"],
                ["Ciento uno", "One hundred one"]
            ]
        }
    },
    {
        "id": "esp-vocab-2a",
        "set": {
            "title": "Vocabulario Unidad 2A",
            "vocab": [
                ["El estudiante", "The male student"],
                ["La estudiante", "The female student"],
                ["La clase", "The class"],
                ["El salón de clase", "The classroom"],
                ["El profesor", "The male teacher"],
                ["La profesora", "The female teacher"],
                ["El mapa", "The map"],
                ["La revista", "The magazine"],
                ["La ventana", "The window"],
                ["La pizarra", "The board"],
                ["El pupitre", "The desk (student desk)"],
                ["La escuela", "The school"],
                ["La pared", "The wall"],
                ["El periódico", "The newspaper"],
                ["La silla", "The chair"],
                ["La puerta", "The door"],
                ["La chica", "The girl"],
                ["El chico", "The boy"],
                ["El amigo", "The male friend"],
                ["La amiga", "The female friend"],
                ["El sacapuntas", "The pencil sharpener"],
                ["La página", "The page"],
                ["La tiza", "The chalk"],
                ["El marcador", "The marker"],
                ["La mochila", "The backpack"],
                ["El lápiz", "The pencil"],
                ["El cesto de papeles / El bote de basura", "The trash can"],
                ["El cuaderno", "The notebook"],
                ["El bolígrafo / La pluma", "The pen"],
                ["El borrador", "The eraser"],
                ["La regla", "The ruler"],
                ["El papel", "The paper"],
                ["El reloj", "The clock"],
                ["El libro", "The book"],
                ["El escritorio", "The desk (teacher desk)"],
                ["Artículos definidos", "Definite articles"],
                ["Artículos indefinidos", "Indefinite articles"],
                ["Yo", "I"],
                ["Tú", "You (informal singular)"],
                ["Él", "He"],
                ["Ella", "She"],
                ["Usted (Ud.)", "You (formal singular)"],
                ["Nosotros / Nosotras", "We (males or mixed / females)"],
                ["Vosotros / Vosotras", "You all (Spain, males or mixed / females)"],
                ["Ellos / Ellas", "They (males or mixed / females)"],
                ["Ustedes", "You all (plural)"],
                ["Ser", "To be (permanent characteristics)"],
                ["¿Quién es ___?", "Who is ___?"],
                ["Él / ella es ___", "He / she is ___"],
                ["¿De dónde son ellos?", "Where are they from?"],
                ["Ellos / ellas son de ___", "They are from ___"],
                ["¿Cómo se llama ___?", "What is ___'s name?"],
                ["Él / ella se llama ___", "His / her name is ___"],
                ["¿De dónde son ustedes?", "Where are you all from?"],
                ["Nosotros somos de ___", "We are from ___"],
                ["¿Quiénes son ellos?", "Who are they?"],
                ["Ellos son ___", "They are ___"],
                ["No sé", "I don't know"],
                ["¿Es de aquí?", "Is he / she from here?"],
                ["¿Quién eres tú?", "Who are you?"],
                ["Yo soy ___", "I am ___"],
                ["¿Qué hay en la clase?", "What is in the class?"],
                ["Comprendo / No comprendo", "I understand / I do not understand"],
                ["¿Qué quiere decir la palabra ___?", "What does the word ___ mean?"],
                ["¿Cómo se dice ___?", "How do you say ___?"],
                ["Comprender", "To understand / to comprehend"]
            ]
        }
    },
    {
        "id": "esp-vocab-2b",
        "set": {
            "title": "Vocabulario Unidad 2B",
            "vocab": [
                ["El colegio", "School"],
                ["El horario", "Schedule"],
                ["La clase de español", "Spanish class"],
                ["La clase de inglés", "English class"],
                ["La clase de matemáticas", "Math class"],
                ["La clase de computación", "Computer class"],
                ["La clase de música", "Music class"],
                ["La clase de arte", "Art class"],
                ["La clase de educación física", "P.E. class"],
                ["La clase de historia", "History class"],
                ["La clase de biología", "Biology / science class"],
                ["La ropa", "Clothes / clothing"],
                ["Pantalón de mezclilla / Los jeans", "Jeans"],
                ["El pantalón", "Pants"],
                ["La camiseta", "T-shirt"],
                ["La camisa", "Shirt"],
                ["Los zapatos", "Shoes"],
                ["Los calcetines", "Socks"],
                ["La falda", "Skirt"],
                ["La blusa", "Blouse"],
                ["El teclado", "Keyboard"],
                ["El ratón", "Mouse"],
                ["La pantalla", "Screen / monitor"],
                ["El teléfono / El celular", "Phone / cell phone"],
                ["La impresora láser", "Laser printer"],
                ["La computadora", "Computer"],
                ["El almuerzo", "Lunch"],
                ["El disco compacto", "Compact disc"],
                ["Los días de la semana", "Days of the week"],
                ["Domingo", "Sunday"],
                ["Lunes", "Monday"],
                ["Martes", "Tuesday"],
                ["Miércoles", "Wednesday"],
                ["Jueves", "Thursday"],
                ["Viernes", "Friday"],
                ["Sábado", "Saturday"],
                ["Los colores", "Colors"],
                ["Negro", "Black"],
                ["Gris", "Gray"],
                ["Azul", "Blue"],
                ["Blanco", "White"],
                ["Verde", "Green"],
                ["Amarillo", "Yellow"],
                ["Rojo", "Red"],
                ["Morado", "Purple"],
                ["Anaranjado", "Orange"],
                ["Marrón / Café", "Brown"],
                ["Rosa", "Pink"],
                ["Estar", "To be (temporary)"],
                ["Estudiar", "To study"],
                ["Hablar", "To talk / speak"],
                ["Llevar", "To take / wear"],
                ["Necesitar", "To need"],
                ["Terminar", "To finish"],
                ["¿Qué?", "What?"],
                ["¿Cómo?", "How?"],
                ["¿Cuánto / Cuántos?", "How much? / How many?"],
                ["¿Cuál(es)?", "Which? / What?"],
                ["¿Dónde?", "Where?"],
                ["¿Quién(es)?", "Who?"],
                ["¿Por qué?", "Why?"],
                ["¿Cuándo?", "When?"],
                ["Yo hablo español", "I speak Spanish"],
                ["¿A qué hora termina la clase?", "What time does the class end?"],
                ["¡Mira!", "Look!"],
                ["¿Cuántas clases tienes?", "How many classes do you have?"],
                ["¿Qué día tienes la clase de ___?", "What day do you have ___ class?"],
                ["¿Bueno? / ¿Hola? / ¿Aló? / ¿Mande?", "Hello? / Hi? (on the phone)"],
                ["¿Con quién hablo?", "With whom am I speaking?"],
                ["¿Puedo hablar con ___?", "Can / may I speak with ___?"],
                ["Él / Ella no está aquí", "He / She is not here"],
                ["¿Cuál es tu número de teléfono?", "What is your phone number?"],
                ["¿Qué necesitas para ___?", "What do you need for ___?"],
                ["Yo necesito ___", "I need ___"],
                ["Yo llevo ___", "I take / wear ___"],
                ["Él / Ella lleva ___", "He / She takes / wears ___"],
                ["¿Hay clase mañana?", "Is there class tomorrow?"],
                ["¿Son tus ___ nuevos(as)?", "Are your ___ new?"],
                ["¿Es tu ___ nuevo(a)?", "Is your ___ new?"],
                ["Yo tengo un examen de computación mañana", "I have a computer test tomorrow"],
                ["El punto", "Period (punctuation)"],
                ["A", "To / at / in"],
                ["Tu / Tus", "Your"]
            ]
        }
    },
    {
        "id": "esp-vocab-3a",
        "set": {
            "title": "Vocabulario Unidad 3A: ¿Adónde vamos en la ciudad?",
            "vocab": [
                ["¿Adónde vamos en la ciudad?", "Where are we going in the city?"],
                ["La biblioteca", "Library"],
                ["El banco", "Bank"],
                ["La ciudad", "City"],
                ["El hotel", "Hotel"],
                ["El restaurante", "Restaurant"],
                ["El cine", "Movie theater"],
                ["El dentista / La dentista", "Dentist"],
                ["La escuela", "School"],
                ["El médico / La médica", "Doctor"],
                ["La oficina", "Office"],
                ["El parque", "Park"],
                ["En autobús", "By bus"],
                ["En avión", "By plane"],
                ["En barco", "By ship"],
                ["En carro", "By car"],
                ["En metro", "By subway"],
                ["La moto / La motocicleta", "Motorcycle"],
                ["El taxi", "Taxi"],
                ["El tren", "Train"],
                ["A pie", "By foot (walking)"],
                ["A caballo", "By horse (horseback riding)"],
                ["La bicicleta", "Bicycle"],
                ["El camión", "Truck"],
                ["El transporte", "Transportation"],
                ["Ir", "To go"],
                ["Caminar", "To walk"],
                ["Querer", "To want"],
                ["Saber", "To know"],
                ["Tomar", "To take"],
                ["¿Adónde?", "Where to?"],
                ["¿Cómo?", "How?"],
                ["¿Cuál? / ¿Cuáles?", "Which? (singular / plural)"],
                ["¿Cuándo?", "When?"],
                ["¿Cuánto? / ¿Cuántos?", "How much? / How many?"],
                ["¿Dónde?", "Where?"],
                ["¿Por qué?", "Why?"],
                ["¿Qué?", "What?"],
                ["¿Quién? / ¿Quiénes?", "Who?"],
                ["¡Vamos!", "Let’s go!"],
                ["Cerca de", "Close to"],
                ["Lejos de", "Far from"],
                ["Te / Le / Les", "To you (informal singular / formal singular / plural)"],
                ["Al", "To the (a + el)"],
                ["Del", "From the / of the (de + el)"],
                ["Te presento a…", "Let me introduce you to…"],
                ["¡Tanto gusto!", "So glad to meet you!"],
                ["¡Encantado! / ¡Encantada!", "Delighted to meet you!"],
                ["El gusto es mío.", "The pleasure is mine."],
                ["Voy", "I go"],
                ["Vas", "You go (informal)"],
                ["Va", "He / She / You (formal) go(es)"],
                ["Vamos", "We go"],
                ["Vais", "You all go (Spain)"],
                ["Van", "They / You all go"],
                ["Un lugar", "A place"],
                ["¡Por supuesto!", "Of course!"],
                ["¡Me encanta!", "I’d love it! / I love it!"],
                ["Hoy no, gracias.", "Not today, thank you."],
                ["¿Otro día?", "Some other day?"],
                ["¿Por qué no...?", "Why don’t we...?"],
                ["Buena idea.", "Good idea."],
                ["¿Adónde vas?", "Where are you going?"],
                ["Voy a la escuela.", "I am going to school."],
                ["Voy a tomar el autobús.", "I am going to take the bus."],
                ["Yo también.", "Me too."],
                ["¿Quieres ir a la fiesta?", "Do you want to go to the party?"],
                ["¡Claro!", "Of course!"],
                ["Quiero ir.", "I want to go."],
                ["¿Cuándo es la fiesta?", "When is the party?"],
                ["¿Sabes quiénes van?", "Do you know who is going?"]
            ]
        }
    },
    {
        "id": "esp-vocab-3b",
        "set": {
            "title": "Vocabulario Unidad 3B: En El Centro",
            "vocab": [
                ["El centro", "Downtown"],
                ["El museo", "Museum"],
                ["El edificio", "Building"],
                ["La tienda", "Store"],
                ["El teatro", "Theater"],
                ["El concierto", "Concert"],
                ["La cantante / El cantante", "Singer"],
                ["La plaza", "Plaza"],
                ["La avenida / La calle", "Avenue / Street"],
                ["El café", "Coffee shop / Coffee"],
                ["La oficina de correos", "Post office"],
                ["La iglesia", "Church"],
                ["La mezquita", "Mosque"],
                ["La sinagoga", "Synagogue"],
                ["La comida", "Food"],
                ["La ensalada", "Salad"],
                ["Los frijoles", "Beans"],
                ["El menú", "Menu"],
                ["El pescado", "Fish"],
                ["La mesera", "Waitress"],
                ["El mesero", "Waiter"],
                ["El pollo", "Chicken"],
                ["La carne", "Meat"],
                ["La hamburguesa", "Hamburger"],
                ["El pan", "Bread"],
                ["El postre", "Dessert"],
                ["Las papas fritas", "French fries"],
                ["La bebida", "Beverage / Drink"],
                ["El agua", "Water"],
                ["El jugo", "Juice"],
                ["El jugo de naranja", "Orange juice"],
                ["El refresco / La soda / La gaseosa", "Soda / Soft drink"],
                ["El chocolate (caliente)", "Hot chocolate"],
                ["El té", "Tea"],
                ["La leche", "Milk"],
                ["Comer", "To eat"],
                ["Hacer", "To do / To make"],
                ["Leer", "To read"],
                ["Saber", "To know (facts)"],
                ["Ver", "To see / To watch / To look"],
                ["Preguntar", "To ask (a question)"],
                ["Ir", "To go"],
                ["Conocer", "To know / To be familiar with"],
                ["Ir + a + infinitivo", "To be going to do something"],
                ["Tomar", "To take / To drink"],
                ["¡Vamos a + infinitivo!", "Let’s go to + infinitive!"],
                ["Ahora", "Now"],
                ["Bueno", "Good / Tasty"],
                ["¡Cómo no!", "Of course!"],
                ["De acuerdo", "Agree / Okay"],
                ["Favorito / Favorita", "Favorite"],
                ["Grande", "Big"],
                ["Hacer una pregunta", "To ask a question"],
                ["Hoy", "Today"],
                ["El momento", "The moment"],
                ["Mucho / Mucha", "Much / A lot"],
                ["Oye", "Listen"],
                ["Pero", "But"],
                ["Pues", "Well"],
                ["Siempre", "Always"]
            ]
        }
    },
];
export const AllESP1Sets: AllSetsInterface[] = [
    SIXA,
    SIXB,
    FiveA,
    FiveB,
    SevenA,
    SevenB,
    ...Unidad1
]