import { AllSetsInterface } from "../AllSets";

export const SPA2_1A: AllSetsInterface = {
	id: "spa2-vocab-1a-la-tecnologia",
	set: {
		title: "Vocabulario Unidad 1A: La tecnología",
		vocab: [
			["la aplicación", "the app / application"],
			["la asignatura", "subject"],
			["bajar (un programa) / descargar", "to download (a program)"],
			["la bandeja de entrada", "inbox"],
			["el/la bloguero/a", "blogger"],
			["el chat en tiempo real", "live chat"],
			["chatear", "to chat"],
			["el celular / el móvil", "cell phone / mobile phone"],
			["compartir", "to share"],
			["la comunicación", "communication"],
			["conectado/a (estar conectado/a)", "connected (to be connected)"],
			["conseguir (e -> i)", "to get; to obtain"],
			["la contaminación ambiental", "environmental pollution"],
			["el dispositivo móvil", "mobile device"],
			["la ecología", "ecology; environment"],
			["el email / el correo electrónico", "email"],
			["encontrar (o -> ue)", "to find"],
			["el fax", "fax"],
			["la impresora", "printer"],
			["la información", "information"],
			["la internet", "the internet"],
			["el mensaje de texto", "text message"],
			["el motor de búsqueda", "search engine"],
			["el mundo", "world"],
			["navegar", "to browse / surf"],
			["el programa", "program"],
			["la red", "network"],
			["la red social", "social network"],
			["seguir (e -> i)", "to follow; to continue"],
			["el sitio web", "website"],
			["subir", "to upload"],
			["la tableta", "tablet"],
			["la tecnología", "technology"],
			["transferir (e -> ie) (video) / la transmisión en vivo", "to transfer / live stream"],
			["tuitear", "to tweet"],
			["el vínculo / el enlace", "link"],
			["la web", "the web"],
			["el wi-fi; la conexión inalámbrica", "wi-fi; wireless connection"]
		]
	}
}

export const SPA2_2A: AllSetsInterface = {
	id: "spa2-vocab-2a-la-rutina-diaria-y-el-cuerpo",
	set: {
		title: "Vocabulario Unidad 2A: La rutina diaria y el cuerpo",
		vocab: [
			["Despertarse (e-ie)", "to wake up"],
			["Ducharse", "to shower"],
			["Afeitarse / rasurarse", "to shave"],
			["Levantarse", "to get up"],
			["Cepillarse los dientes", "to brush one's teeth"],
			["Peinarse", "to comb one's hair"],
			["Bañarse", "to bathe; to take a bath"],
			["Lavarse las manos", "to wash one's hands"],
			["Maquillarse", "to put on makeup"],
			["Ponerse", "to put on"],
			["Quitarse", "to take off"],
			["Vestirse (e-i)", "to get dressed"],
			["Acostarse (o-ue)", "to go to bed"],
			["Irse", "to leave; to go away"],
			["Secarse", "to dry oneself"],
			["La boca", "mouth"],
			["La cara", "face"],
			["El codo", "elbow"],
			["El desodorante", "deodorant"],
			["La ducha / la regadera", "shower"],
			["El espejo", "mirror"],
			["El grifo / la llave", "faucet"],
			["El inodoro", "toilet"],
			["El jabón", "soap"],
			["El lavabo / el lavamanos", "sink"],
			["El maquillaje", "makeup"],
			["El peine", "comb"],
			["La tina / la bañera", "bathtub"],
			["La toalla", "towel"],
			["El pelo / el cabello", "hair"],
			["El desayuno", "breakfast"],
			["La cena", "dinner"],
			["El almuerzo", "lunch"],
			["La merienda", "snack"],
			["Desayunar(se)", "to eat breakfast"],
			["Almorzar (o-ue)", "to eat lunch"],
			["Cenar", "to eat dinner"],
			["El cepillo de dientes", "toothbrush"],
			["La pasta de dientes", "toothpaste"],
			["La máquina de afeitar", "razor"],
			["El papel higiénico", "toilet paper"],
			["El secador de pelo", "hair dryer"],
			["Abrir/cerrar (la llave de agua)", "to open/close the water tap"],
			["Bajar/echar el agua", "to flush the toilet"]
		]
	}
}

export const SPA2_3: AllSetsInterface = {
	id: "spa2-vocab-3-en-el-restaurante",
	set: {
		title: "Vocabulario Unidad 3: En el restaurante",
		vocab: [
			["el aderezo", "dressing"],
			["el camarero / la camarera", "waiter / waitress"],
			["el cocinero / la cocinera", "cook / chef"],
			["el pimiento", "pepper"],
			["el sabor", "flavor; taste"],
			["el salero", "salt shaker"],
			["la azucarera", "sugar bowl"],
			["la cuenta", "bill; check"],
			["la mayonesa", "mayonnaise"],
			["la mostaza", "mustard"],
			["la propina", "tip"],
			["la salsa", "sauce"],
			["la salsa de tomate", "tomato sauce; ketchup"],
			["delicioso/a", "delicious"],
			["lleno/a", "full"],
			["rico/a", "tasty; delicious"],
			["diferente", "different"],
			["principal", "main"],
			["aconsejar", "to advise"],
			["agregar", "to add"],
			["decidir", "to decide"],
			["probar (o-ue)", "to try; to taste"],
			["servir (e-i)", "to serve"]
		]
	}
}

export const SPA2_4A: AllSetsInterface = {
	id: "spa2-vocab-4a-mi-ninez",
	set: {
		title: "Vocabulario Unidad 4A: En el parque de atracciones, en el zoológico y mi niñez",
		vocab: [
			["el algodón de azúcar", "cotton candy"],
			["la atracción", "ride; attraction"],
			["los carros chocones", "bumper cars"],
			["el carrusel", "carousel"],
			["el desfile", "parade"],
			["los fuegos artificiales", "fireworks"],
			["el globo", "balloon"],
			["la golosina / el dulce", "candy; treat"],
			["la montaña rusa", "roller coaster"],
			["las palomitas de maíz", "popcorn"],
			["la rueda de Chicago / de la fortuna", "Ferris wheel"],
			["chistoso/a", "funny"],
			["fascinante", "fascinating"],
			["feroz", "fierce"],
			["maravilloso/a", "wonderful"],
			["salvaje", "wild"],
			["gritar", "to yell; to shout"],
			["haber", "to have; there to be"],
			["imaginarse", "to imagine"],
			["molestar", "to bother"],
			["la cámara", "camera"],
			["como", "like"],
			["la visita", "visit"],
			["el animal", "animal"],
			["el camello", "camel"],
			["la cebra", "zebra"],
			["el elefante", "elephant"],
			["el flamenco", "flamingo"],
			["el gorila", "gorilla"],
			["el guía / la guía", "guide"],
			["el hipopótamo", "hippopotamus"],
			["la iguana", "iguana"],
			["el zoológico", "zoo"],
			["la jirafa", "giraffe"],
			["el león", "lion"],
			["el mono", "monkey"],
			["la pantera", "panther"],
			["la selva", "jungle"],
			["la serpiente", "snake"],
			["el tigre", "tiger"],
			["la tortuga", "turtle"],
			["el juguete", "toy"],
			["las muñecas / los muñecos", "dolls / toy figures"],
			["las caricaturas / los dibujos animados", "cartoons"],
			["el muñeco de peluche", "stuffed animal"],
			["el columpio", "swing"],
			["divertido/a", "fun; entertaining"],
			["impaciente", "impatient"],
			["obediente", "obedient"],
			["sociable", "sociable"],
			["tímido/a", "shy"],
			["consentido/a", "spoiled"],
			["contar chistes", "to tell jokes"],
			["saltar la cuerda", "to jump rope"],
			["ser travieso", "to be mischievous"],
			["fingir", "to pretend"],
			["llorar", "to cry"],
			["portarse bien / mal", "to behave well / badly"],
			["divertirse", "to have fun"],
			["pelearse", "to fight"],
			["compartir", "to share"]
		]
	}
}

export const SPA2_5B_9A_9B: AllSetsInterface = {
	id: "spa2-vocab-de-compras",
	set: {
		title: "Vocabulario: De compras",
		vocab: [
			["el abrigo", "coat"],
			["la blusa", "blouse"],
			["la bota", "boot"],
			["la bufanda", "scarf"],
			["los calcetines", "socks"],
			["la camisa", "shirt"],
			["la camiseta", "T-shirt"],
			["la chaqueta", "jacket"],
			["las chanclas", "flip-flops"],
			["el cinturón", "belt"],
			["la corbata", "tie"],
			["la falda", "skirt"],
			["las gafas de sol", "sunglasses"],
			["la gorra", "cap"],
			["el gorro", "winter hat"],
			["el guante", "glove"],
			["el impermeable", "raincoat"],
			["los jeans", "jeans"],
			["las mangas (cortas / largas)", "sleeves (short / long)"],
			["las medias", "stockings"],
			["los pantalones", "pants"],
			["las pantuflas", "slippers"],
			["el pijama", "pajamas"],
			["la ropa interior", "underwear"],
			["las sandalias", "sandals"],
			["los shorts", "shorts"],
			["el sombrero", "hat"],
			["la sudadera", "sweatshirt"],
			["la sudadera con capucha", "hoodie"],
			["el suéter", "sweater"],
			["el traje (de baño)", "swimsuit"],
			["el vestido", "dress"],
			["las zapatillas / los tenis", "sneakers"],
			["el zapato (bajo / de tacón)", "shoe (flat / high-heeled)"],
			["alguien", "someone"],
			["alguno/a", "some; any"],
			["nada", "nothing"],
			["nadie", "nobody"],
			["ninguno/a", "none; no one"],
			["algún / algunos / alguna/s", "some"],
			["ningún / ninguna", "no; not any"],
			["barato/a", "cheap"],
			["caro/a", "expensive"],
			["elegante", "elegant"],
			["informal", "casual"],
			["ligero/a", "light"],
			["amarillo/a", "yellow"],
			["anaranjado/a", "orange"],
			["azul", "blue"],
			["blanco /a", "white"],
			["gris", "gray"],
			["marrón, de color café", "brown"],
			["morado/a", "purple"],
			["negro/a", "black"],
			["rojo/a", "red"],
			["rosado/a, de color rosa", "pink"],
			["verde", "green"],
			["el algodón", "cotton"],
			["el centro comercial", "mall"],
			["el cuero", "leather"],
			["el departamento", "department store"],
			["el hombre", "man"],
			["la lana", "wool"],
			["la mujer", "woman"],
			["ni… ni", "neither...nor"],
			["o… o", "either...or"],
			["quedarle algo a alguien", "to fit someone"],
			["quedarle bien a uno", "to fit someone well"],
			["la seda", "silk"],
			["las vacaciones", "vacation"],
			["ahorrar", "to save (money)"],
			["combinar / hacer juego", "to match; to go together"],
			["contar (o -> ue)", "to count"],
			["gastar", "to spend"],
			["prometer", "to promise"],
			["vender", "to sell"],
			["a cuadros", "plaid"],
			["a rayas", "striped"],
			["la cadena", "chain"],
			["la caja", "cash register; box"],
			["el cajero / la cajera", "cashier"],
			["desteñido/a", "faded"],
			["el diamante", "diamond"],
			["estampado/a", "printed; patterned"],
			["la joya", "jewel"],
			["la joyería", "jewelry store"],
			["la prenda", "garment; item of clothing"],
			["probarse (ue)", "to try on"],
			["el rubí", "ruby"],
			["la talla", "size"],
			["el surtido", "selection; assortment"],
			["la tela", "fabric"],
			["el tipo", "type"],
			["la variedad", "variety"],
			["el vestidor", "fitting room"],
			["el anillo", "ring"],
			["el arete", "earring"],
			["la billetera / la cartera", "wallet"],
			["el cambio", "change"],
			["el collar", "necklace"],
			["el dependiente / la dependienta", "salesclerk"],
			["el efectivo", "cash"],
			["el escaparate", "store window"],
			["la etiqueta", "tag"],
			["la oferta", "sale; offer"],
			["el oro", "gold"],
			["el paraguas", "umbrella"],
			["el perfume", "perfume"],
			["la plata", "silver"],
			["el probador", "dressing room"],
			["la pulsera", "bracelet"],
			["el recibo", "receipt"],
			["el regalo", "gift"],
			["el tamaño", "size"],
			["la tarjeta de crédito", "credit card"]
		]
	}
}

export const SPA2_7A: AllSetsInterface = {
	id: "spa2-vocab-7a-en-las-noticias-y-los-programas-de-television",
	set: {
		title: "Vocabulario Unidad 7A: En las noticias y los programas de televisión",
		vocab: [
			["el accidente", "accident"],
			["las actividades normales", "normal activities"],
			["los acontecimientos", "events; happenings"],
			["la catástrofe", "disaster"],
			["la celebración", "celebration"],
			["la destrucción", "destruction"],
			["la herida", "wound"],
			["el huracán", "hurricane"],
			["el misterio", "mystery"],
			["la ocasión", "occasion"],
			["la protesta", "protest"],
			["la reunión", "meeting"],
			["el reportero / la reportera", "reporter"],
			["el robo", "robbery"],
			["el temblor", "earthquake; tremor"],
			["el testigo", "witness"],
			["los sucesos", "events; incidents"],
			["lastimar(se)", "to hurt; to injure oneself"],
			["morder (o-ue)", "to bite"],
			["romper", "to break"],
			["herido/a", "injured"],
			["serio/a", "serious"],
			["la actriz, el actor", "actress, actor"],
			["el anuncio comercial", "commercial"],
			["el autógrafo", "autograph"],
			["el canal", "channel"],
			["el / la cantante", "singer"],
			["la comedia", "comedy"],
			["el concurso", "contest; game show"],
			["los dibujos animados", "cartoons"],
			["el musical", "musical"],
			["el noticiero", "newscast"],
			["el periodista", "journalist"],
			["el / la personaje", "character"],
			["el público", "audience"],
			["las telenovelas", "soap operas"],
			["extranjera", "foreign"],
			["famoso", "famous"],
			["nacional", "national"],
			["aburrir(se)", "to bore; to get bored"],
			["bostezar", "to yawn"],
			["estar de acuerdo", "to agree"],
			["fracasar", "to fail"],
			["grabar", "to record"],
			["informar", "to inform; to report"],
			["morirse de risa", "to die laughing"],
			["mostrar", "to show"],
			["opinar", "to give an opinion"],
			["participar", "to participate"],
			["tener éxito", "to be successful"]
		]
	}
}

export const AllSPA2: AllSetsInterface[] = [
	SPA2_1A,
	SPA2_2A,
	SPA2_3,
	SPA2_4A,
	SPA2_5B_9A_9B,
	SPA2_7A
]

