import { AllSetsInterface } from "../AllSets"

export const tnofdpreface: AllSetsInterface = {
    "id": "tnofd-preface",
    "set": {
      "title": "Narrative of the Life of Frederick Douglass: Preface and Letter Study Guide",
      "vocab": [
        ["Frederick Douglass", "An African American social reformer, abolitionist, orator, writer, and statesman who escaped from slavery and became a national leader of the abolitionist movement."],
        ["William Lloyd Garrison", "Founder of the American Anti-Slavery Society and editor who promoted abolitionism and supported Douglass’s career."],
        ["Wendell Phillips", "Abolitionist and president of the American Anti-Slavery Society who wrote a supportive letter to Douglass."],
        ["Preface", "An introductory section of a book written by someone other than the author, often to provide context, credibility, or perspective."],
        ["Slave narrative", "A genre of autobiographical writing that recounts the experiences of enslaved people, often highlighting the brutality of slavery and the author’s path to freedom."],
        ["Authenticity", "The quality of being genuine or true; in the context of Douglass’s narrative, the truthfulness of his account."],
        ["Abolitionist", "A person who advocated for the immediate ending of slavery."],
        ["Anti-Slavery Society", "An organization founded to promote the abolition of slavery and support the rights of African Americans."],
        ["Nantucket Convention", "An 1841 anti-slavery meeting where Douglass first spoke publicly about his life as a slave."],
        ["Oration", "A formal speech, especially one given on a ceremonial occasion."],
        ["Patrick Henry", "An American revolutionary known for his speeches advocating independence from Britain, referenced to emphasize Douglass's oratorical skill."],
        ["Head and heart", "A phrase used by Garrison to describe Douglass’s combination of intellect and emotional appeal."],
        ["Racial inferiority", "A false belief that one race is naturally less capable or intelligent than others; Garrison refuted this claim regarding African Americans."],
        ["Mental deterioration", "The decline in mental abilities, used by Garrison to illustrate the effects of slavery on both black and white people."],
        ["Chesapeake Bay soliloquy", "A passage in Douglass’s narrative highlighting his reflective and sublime thinking."],
        ["Skeptics", "People who doubt or refuse to believe in the reported abuses of slavery."],
        ["False Christianity", "A critique by Douglass and Garrison of the hypocritical religious justifications for slavery by slaveholders."],
        ["Fugitive Slave Laws", "Laws requiring that escaped slaves be returned to their owners, even from free states."],
        ["Representative depiction", "The idea that Douglass’s individual experiences symbolize the broader experiences of enslaved people."],
        ["Duality", "The concept of two coexisting aspects; in Douglass’s narrative, the contrast between his enslaved past and his educated, free self."],
        ["Sentimentalism", "A literary style valuing emotion, pathos, and moral feeling to persuade readers."],
        ["Preface function", "To prepare readers for the narrative, attest to its truthfulness, and frame the author’s story for political or moral purposes."],
        ["Editor authority", "The implicit control editors have in framing the narrative for audiences, often white audiences in Douglass’s time."],
        ["Political argument", "A line of reasoning aimed at advocating for societal change, such as abolition in Douglass’s narrative."],
        ["Pro-slavery refutation", "Arguments in the prefaces countering claims that slavery was natural or non-violent."],
        ["Maryland slavery", "Douglass’s location of enslavement, considered relatively mild, highlighting that cruelty existed even in less harsh states."],
        ["Oratorical genius", "Douglass’s exceptional skill in public speaking, emphasized by Garrison."],
        ["Superior manhood", "Garrison’s description of Douglass’s moral and intellectual excellence as evidence against claims of racial inferiority."],
        ["Disparity of selves", "The contrast between Douglass as a former slave and as the free, educated narrator."],
        ["Autobiography", "A self-written account of one’s life, often exploring personal growth and experiences."],
        ["Slave oppression", "The systemic dehumanization, brutality, and denial of rights experienced by enslaved people."],
        ["Emotional power", "The ability of Douglass’s narrative to evoke sympathy and moral reflection in readers."],
        ["Moral feeling", "An ethical awareness of right and wrong, often expressed through emotion in literature."],
        ["Protection appeal", "Garrison’s request to audiences to safeguard Douglass, symbolizing protection for all fugitive slaves."],
        ["Historical comparison", "Garrison’s reference to American revolutionaries to contextualize Douglass’s courage and significance."],
        ["Pathos", "A rhetorical strategy appealing to emotion to influence readers or listeners."],
        ["Slave brutality", "The physical, sexual, and psychological abuse faced by enslaved individuals."],
        ["Slave testimony", "The inability of enslaved people to testify against white individuals in court."],
        ["Narrative truthfulness", "The confirmed honesty of Douglass’s account as emphasized by Garrison and Phillips."],
        ["Selective history", "The incomplete and biased records of slavery created by slaveholders, prior to narratives like Douglass’s."],
        ["Political safety", "The concern for Douglass’s protection due to the risk of recapture."],
        ["Declaration of Independence parallel", "Phillips compares Douglass’s risk in publishing his narrative to the risks taken by the signers of the Declaration."],
        ["Asylum for fugitive slaves", "Phillips’s call for Massachusetts to provide legal protection for escaped slaves."],
        ["Literary merit", "The quality of Douglass’s writing to convey deep feeling and intellectual insight."],
        ["Sublime mind", "A term Garrison uses to describe Douglass’s intellectual and moral brilliance."],
        ["Personal life vs. political message", "Douglass’s narrative blends individual experience with a broader commentary on slavery."],
        ["Representative substitution", "The use of Douglass’s story to stand for the experiences of all enslaved people."],
        ["Sensationalized skepticism", "Critics who refuse to accept the severity of slavery’s abuses."],
        ["Audience persuasion", "The method by which Douglass and his supporters encourage moral and political action."],
        ["Slaveholder hypocrisy", "The contradiction of professed Christian values and the practice of slavery."],
        ["Historical context", "Understanding the period, laws, and societal norms influencing Douglass’s narrative."],
        ["Narrative power", "The effectiveness of Douglass’s story to move and educate readers."],
        ["Personal danger", "The risk Douglass faced by revealing the true identities of himself and his masters."],
        ["Educational attainment", "Douglass’s acquisition of literacy and knowledge as a tool for liberation."],
        ["Escaping slavery", "Douglass’s journey from being enslaved to achieving freedom."],
        ["Double role", "Douglass’s simultaneous position as narrator of his past and protagonist of his story."],
        ["Cultural influence", "The effect of Douglass’s narrative on 19th-century audiences and abolitionist thought."],
        ["Slave narrative prefaces", "Introductions by white editors to legitimize and frame the slave’s account for readers."],
        ["Abolitionist network", "The group of Northern supporters, like Garrison and Phillips, who aided escaped slaves and promoted abolition."],
        ["Literary emotional appeal", "Using expressive writing to elicit empathy and ethical consideration from readers."],
        ["Moral persuasion", "The strategy of convincing readers of the immorality of slavery through narrative and argument."],
        ["Representation of slavery", "The depiction of the enslaved experience, intended to reflect widespread conditions, not just individual cases."]
      ]
    }
}
  
export const tnofd12: AllSetsInterface = {
    "id": "tnofd-chapters-1-and-2",
    "set": {
      "title": "Narrative of the Life of Frederick Douglass: Chapters I & II Study Guide",
      "vocab": [
        ["Talbot County, Maryland", "The birthplace of Frederick Douglass, where he was born into slavery."],
        ["Birth year ignorance", "Enslaved people were often denied knowledge of their birth years to maintain control over them."],
        ["Harriet Bailey", "Frederick Douglass’s mother, separated from him shortly after birth."],
        ["Maternal separation", "A common practice in slavery to weaken family bonds and assert control over enslaved people."],
        ["Mixed-race slavery", "Children born to enslaved women and white men, often suffering harsher conditions due to social prejudice and legal enslavement laws."],
        ["Captain Anthony", "Douglass’s first master, known for his cruelty and oversight of the enslaved."],
        ["Mr. Plummer", "The overseer under Captain Anthony, described as drunk and violent, frequently whipping enslaved people."],
        ["Aunt Hester whipping", "A pivotal moment where young Douglass witnesses brutal abuse, marking his first encounter with slavery's horror."],
        ["Slaveholder rape", "A practice in which enslavers sexually exploited enslaved women, producing children who would also be enslaved."],
        ["Law of partus sequitur ventrem", "Legal principle ensuring children of enslaved women inherited the status of their mothers, profiting slaveholders."],
        ["Captain Anthony family", "Includes sons Andrew and Richard and daughter Lucretia; integrated into the larger plantation system."],
        ["Captain Thomas Auld", "Husband of Lucretia, involved in overseeing enslaved labor and trade."],
        ["Colonel Lloyd", "Owner of the central plantation; Captain Anthony and other overseers report to him."],
        ["Great House Farm", "Colonel Lloyd’s central plantation, symbolic of the hub of slave labor and control."],
        ["Monthly allowances", "Minimal rations given to enslaved people, such as pork, fish, or cornmeal, reflecting subsistence living."],
        ["One blanket, one set of clothing", "Illustrates the harsh material conditions and neglect of enslaved people’s basic needs."],
        ["Mr. Severe", "A cruel overseer whose name reflects his harsh treatment of enslaved laborers."],
        ["Mr. Hopkins", "Replaced Mr. Severe and was comparatively fair and less profane."],
        ["Enslaved people songs", "Spontaneous songs sung by enslaved people that appear joyful but are actually laments about slavery."],
        ["Slave song meaning", "Douglass later interprets the songs as expressions of sorrow, complaint, and hope under oppression."],
        ["Dehumanization", "The process by which enslaved people were treated as less than human through systemic cruelty and control."],
        ["Psychological control", "Slavery’s method of instilling fear and compliance, making enslaved people complicit in their own oppression."],
        ["Physical abuse", "Use of whipping, beatings, and other violence to maintain power over enslaved people."],
        ["Motif of female abuse", "Repeated imagery of enslaved women being whipped, emphasizing the brutality and gendered violence of slavery."],
        ["Narrative authority", "Douglass’s credibility as a former slave who can interpret and analyze the institution of slavery for readers."],
        ["Doubleness of self", "The dual perspective of Douglass as both former enslaved person and educated, free narrator."],
        ["Mediator role", "Douglass’s position as a bridge between enslaved individuals and Northern white audiences."],
        ["Slave ignorance", "A deliberate tactic by enslavers to keep enslaved people uneducated and powerless."],
        ["Analytical narrative structure", "Douglass presents personal experiences and then generalizes them to reveal the system of slavery."],
        ["Educational attainment", "Douglass’s learning and literacy as tools for personal liberation and authority."],
        ["Witnessing violence", "Douglass’s early exposure to cruelty, particularly Aunt Hester’s whipping, shaping his understanding of slavery."],
        ["Slaveholder cruelty", "The consistent abuse, control, and exploitation inflicted by those owning slaves."],
        ["Depravity of slavery", "The moral corruption of both enslavers and the enslaved as a result of systemic oppression."],
        ["Exposing slavery", "Douglass’s goal to educate readers about the realities of enslaved life, countering pro-slavery narratives."],
        ["Motif", "A recurring theme or symbol, such as the abuse of women in Douglass’s narrative, used to illustrate broader truths."],
        ["Psychological initiation", "The moment Douglass realizes the mental as well as physical horror of slavery."],
        ["Emotional impact of songs", "Slave songs convey deep sorrow and suffering, which Douglass interprets as an early insight into slavery’s cruelty."],
        ["Northern misunderstanding", "Many Northerners mistakenly thought slave songs were joyful, illustrating their ignorance of slavery."],
        ["Slaveholder power tactics", "Methods used to control enslaved people, including family separation, ignorance, and physical violence."],
        ["Slave labor", "The work forced upon enslaved people on plantations, often grueling and exhausting."],
        ["Slave community", "Enslaved people maintained bonds and cultural expression, such as through songs and communal interactions."],
        ["Narrative purpose", "Douglass’s story serves both as autobiography and as a political argument against slavery."],
        ["Public argument", "The broader social and moral lesson Douglass aims to convey to his audience."],
        ["Representation of all slaves", "Douglass’s personal experiences are framed as typical of enslaved people in general."],
        ["Horrors of slavery", "The combination of physical abuse, sexual exploitation, psychological control, and dehumanization."],
        ["Dehumanization of women", "Women are often used in the narrative to highlight the extreme cruelty of slavery."],
        ["Safety and fear", "Enslaved people’s fear for their own safety reinforces their compliance with slavery."],
        ["Maturation through trauma", "Douglass grows aware of slavery’s evils through witnessing abuse and understanding systemic oppression."],
        ["Slaveholder sexual exploitation", "The systematic sexual abuse of enslaved women to increase the enslaved population and profit."],
        ["Narrative tone", "Douglass’s voice combines authority, reflection, and moral insight to engage readers."],
        ["Perspective shift", "Douglass interprets his past experiences with new understanding as a free, educated man."],
        ["Emotional distance", "Douglass maintains a degree of separation from his own suffering to analyze slavery effectively."],
        ["Slave songs as testimony", "Songs reveal the lived experiences and hidden suffering of enslaved communities."],
        ["Plantation hierarchy", "The structure of slaveholding with colonels, captains, overseers, and enslaved laborers."],
        ["Slave rations", "Minimal provisions provided by enslavers, often insufficient for health and comfort."],
        ["Slave clothing", "Typically one set of clothing per year, reflecting deprivation and control."],
        ["Slave lodging", "Harsh living conditions with no proper beds and uncomfortable floors."],
        ["Colonel Lloyd’s supervision", "He oversaw multiple plantations, enforcing control over a large enslaved population."],
        ["Slaveholder wealth", "Tobacco, corn, and wheat plantations provided the economic basis for slavery and exploitation."],
        ["Northern audience education", "Douglass’s narrative seeks to reveal slavery’s cruelty to those unaware in the North."]
      ]
    }
  }

  export const tnofd34: AllSetsInterface = {
    "id": "tnofd-chatpers-3-and-4",
    "set": {
      "title": "Narrative of the Life of Frederick Douglass: Chapters III & IV Study Guide",
      "vocab": [
        ["Colonel Lloyd", "Owner of the central plantation where Douglass grew up; extremely wealthy and cruel."],
        ["Cultivated garden", "Colonel Lloyd's garden where enslaved people are tempted to steal fruit, punished with tar and whipping."],
        ["Tar on fence", "Method used by Colonel Lloyd to catch enslaved people stealing fruit from his garden."],
        ["Old Barney and Young Barney", "Father and son enslaved men in charge of Colonel Lloyd’s stables, whipped for minor faults."],
        ["Punishment without complaint", "Enslaved people were expected to receive punishment silently, demonstrating total control."],
        ["Colonel Lloyd’s absenteeism", "Despite never seeing many enslaved people, Lloyd maintained control and enforced punishment through others."],
        ["Truth-telling punishment", "Enslaved people punished for telling the truth about their masters, as shown by the man sold to Georgia."],
        ["Enslaved people competition", "Slaves sometimes argued over whose master was kinder, reflecting survival tactics under oppression."],
        ["Mr. Austin Gore", "Cruel and cunning overseer replacing Mr. Hopkins, total domination over enslaved people."],
        ["Demby", "Enslaved man shot by Mr. Gore after refusing to leave a creek, exemplifying arbitrary punishment."],
        ["Mr. Gore’s murder of Demby", "Illustrates the total impunity of overseers and normalized violence in slavery."],
        ["Mr. Thomas Lanman", "Maryland slaveholder who killed two enslaved people without investigation."],
        ["Mrs. Hick", "Killed a female servant; example of unpunished violence toward enslaved people."],
        ["Beal Bondly", "Neighbor of Colonel Lloyd who shot an elderly enslaved man, showing common disregard for Black lives."],
        ["Picaresque style", "Narrative style featuring episodic storytelling, as seen in Douglass’s recounting of various slavery incidents."],
        ["Narrative authenticity", "Douglass uses detailed depictions to convince skeptical readers of the truth of slavery."],
        ["Mental dehumanization", "Slavery damages the minds of enslaved people, fostering paranoia and fear."],
        ["Inconsistent punishment", "Slaveholders punished arbitrarily, creating psychological instability among the enslaved."],
        ["Slave paranoia", "Enslaved people had to remain constantly alert and fearful to survive arbitrary punishment."],
        ["Prejudice and dishonesty among slaves", "Natural responses to oppressive conditions, not moral failings."],
        ["Irony", "Literary device Douglass uses to highlight the discrepancy between supposed justice and actual cruelty."],
        ["Mr. Gore’s 'first-rate overseer'", "Example of Douglass’s ironic tone; respected for cruelty, not fairness."],
        ["Psychological violence", "The mental suffering inflicted on enslaved people as a key tool of slavery."],
        ["Physical violence", "The whippings, beatings, and murders that enforce slavery."],
        ["Slave compliance", "The forced obedience of enslaved people through fear of punishment."],
        ["Slave mind games", "Techniques masters used to manipulate enslaved people psychologically."],
        ["Witnessing injustice", "Douglass observes and records acts of cruelty to illustrate systemic oppression."],
        ["Slave vulnerability", "Enslaved people are made helpless and fearful through arbitrary punishment."],
        ["Enslaved humanization", "Douglass emphasizes enslaved people’s reason and emotion to argue their humanity."],
        ["Slave hierarchy", "Structure of plantation authority with colonels, overseers, and enslaved workers."],
        ["Slave invisibility", "Enslaved people’s experiences are ignored or doubted by society."],
        ["White skepticism", "19th-century readers often doubted the truth of Douglass’s accounts due to racial prejudice."],
        ["Scene detail", "Douglass includes vivid descriptions, like old Barney revealing his bald head, to prove authenticity."],
        ["Dramatic recounting", "Douglass narrates events, such as Mr. Gore shooting Demby, with suspense and clarity to engage readers."],
        ["Slaveholder impunity", "Slaveholders and overseers often commit murder without legal consequences."],
        ["Moral argument", "Douglass uses examples of cruelty to show slavery’s immorality."],
        ["Slave community observation", "Douglass studies behaviors, songs, and interactions to reveal slavery’s effects."],
        ["Narrative as treatise", "Douglass combines personal account with political argument against slavery."],
        ["Slave coping strategies", "Pretense of contentment and competition among enslaved people to navigate oppression."],
        ["Slave oppression reinforcement", "Stories of other enslaved people strengthen Douglass’s argument about the system."],
        ["Empathy development", "Douglass educates white readers to feel the suffering of enslaved individuals."],
        ["Moral paradox", "Enslavers are outwardly respected yet morally corrupt and violent."],
        ["Slave resistance", "Limited forms of resistance or survival strategies under oppressive conditions."],
        ["Violence normalization", "Repeated examples of unpunished killings establish cruelty as systemic."],
        ["Slave dehumanization motif", "Recurring instances of violence illustrate the erasure of enslaved people’s dignity."],
        ["Slaveholder pride", "Overseers like Mr. Gore maintain dominance and obedience while seeking favor from masters."],
        ["Slaveholder hierarchy enforcement", "Overseers perform punishment to reinforce the master’s authority."],
        ["Slaveholder cruelty as social norm", "Arbitrary violence is accepted and expected in the plantation system."],
        ["Slave psychological insight", "Douglass analyzes enslaved people’s behaviors as rational responses to oppression."],
        ["Slave moral reasoning", "Despite oppression, enslaved people make choices to survive, reflecting human morality."],
        ["Narrative purpose verification", "Use of detailed scenes ensures readers understand the authenticity and scope of slavery."],
        ["Episodic storytelling", "Chapters III and IV recount discrete events connected by Douglass’s observations and moral analysis."],
        ["Slave observation as evidence", "Douglass uses the actions and fates of other enslaved individuals to substantiate his claims."],
        ["Douglass as mediator", "He interprets slavery for Northern readers, bridging the gap between experience and understanding."],
        ["Slave experience commonality", "Douglass emphasizes that the abuses he witnessed were typical, not exceptional."],
        ["Psychological resilience", "Enslaved people adapt behaviors to endure mental and physical hardships."],
        ["Slaveholder cruelty verification", "Detailed accounts provide proof to skeptical audiences of widespread abuse."],
        ["Irony in narrative", "Douglass uses irony to highlight moral contradictions, like the praise of cruel overseers."],
        ["Slave moral complexity", "Even under extreme oppression, enslaved people retain ethical awareness and reason."],
        ["Slave narrative evidence", "First-hand accounts like Douglass’s challenge pro-slavery arguments and highlight systemic injustice."]
      ]
    }
  }

export const tnofd56: AllSetsInterface = {
    "id": "tnofd-chapters-5-and-6",
    "set": {
      "title": "Narrative of the Life of Frederick Douglass: Chapters V & VI Study Guide",
      "vocab": [
        ["Child labor in slavery", "Children were not strong enough to work in fields but still suffered from cold, hunger, and harsh conditions."],
        ["Corn mush trough", "Communal feeding system where only strongest children got enough to eat."],
        ["Baltimore transfer", "Douglass sent to live with Hugh Auld in Baltimore, marking a major turning point in his life."],
        ["Providence", "Douglass’s belief that his move to Baltimore was guided by divine intervention, giving him hope."],
        ["Mrs. Sophia Auld", "Hugh Auld’s wife who initially treats Douglass kindly and begins teaching him to read."],
        ["Hugh Auld", "Sophia Auld’s husband, who insists Douglass must not be educated, explaining the logic of slavery."],
        ["Education as freedom", "Douglass’s insight that literacy and knowledge are the keys to escaping slavery."],
        ["Slaveholding disease", "The moral corruption that slavery inflicts on slaveholders, exemplified by Sophia Auld’s transformation."],
        ["Urban slavery", "Enslaved people in cities like Baltimore experienced relatively greater freedom and less direct cruelty."],
        ["Hamiltons’ cruelty", "Example of urban slave abuse: Mrs. Hamilton beats young women into injury, showing exceptions to urban kindness."],
        ["Dichotomy of self", "Douglass contrasts his free, educated, literate self with his abused, enslaved body, sometimes collapsing the distinction."],
        ["Frostbite imagery", "Douglass describes childhood frostbite, dramatizing the physical suffering and his eventual literate self."],
        ["City versus countryside motif", "Cities symbolize intellectual opportunity and relative freedom, while rural plantations symbolize extreme restriction."],
        ["Slaveholder self-deception", "Slaveowners justify slavery and corrupt themselves morally and spiritually to maintain control."],
        ["Sophia Auld as victim", "Her moral decline illustrates how slavery corrupts the enslaver, making her both perpetrator and victim."],
        ["Gender stereotype", "Sophia depicted as sympathetic, virtuous woman, reflecting 19th-century ideals, reinforcing readers’ sympathy."],
        ["Turning points in Douglass’s youth", "1) Witnessing Aunt Hester’s whipping, 2) Realizing the importance of literacy after Hugh Auld forbids teaching."],
        ["Education prohibition revelation", "Douglass learns that depriving enslaved people of knowledge is a tool for keeping power over them."],
        ["Rhetorical antithesis", "Douglass contrasts his goals with Hugh Auld’s: 'What [Hugh Auld] most loved, that I most hated.'"], 
        ["Literacy as liberation", "Acquiring reading and writing skills empowers Douglass to envision freedom."],
        ["Urban intellectual exposure", "Baltimore allows Douglass to interact with diverse people and ideas, fostering his mental emancipation."],
        ["Slave narrative structure", "Douglass combines personal history with moral and political analysis to persuade readers."],
        ["Narrative honesty", "Douglass emphasizes his own limited hardships to enhance credibility and realism."],
        ["Psychological insight", "Douglass observes how slavery affects minds, including both enslaved and enslavers."],
        ["Slave morality", "Enslaved people retain reasoning and ethical capacity, despite systemic oppression."],
        ["Symbolic freedom", "Baltimore represents proximity to freedom and opportunity compared to rural plantation life."],
        ["Slaveholder morality", "Slaveholding turns individuals cruel, teaches corruption, and erodes human qualities."],
        ["Slave-narrator doubleness", "Douglass presents himself as both victim and interpreting narrator, bridging past and present selves."],
        ["Providential optimism", "Belief in divine guidance gives Douglass hope and resilience during childhood hardships."],
        ["Slave education as rebellion", "Pursuit of literacy is an act of resistance against the institution of slavery."],
        ["Sophia’s moral corruption", "Illustrates how even well-intentioned people are warped by slavery’s power dynamics."],
        ["Douglass’s alignment with authority", "He frames his learning in opposition to Hugh Auld’s authority, using male power as motivation."],
        ["Slave psychological doubling", "Douglass’s literate self analyzes, records, and interprets the experiences of his enslaved self."],
        ["Slave liberation motif", "Knowledge and education appear repeatedly as the path to freedom and self-determination."],
        ["Childhood resilience", "Despite suffering from cold, hunger, and abuse, Douglass survives and adapts, showing early strength."],
        ["Slave observation", "Douglass records both his experiences and those of others to illustrate systemic slavery."],
        ["Master-slave relationship", "Explored through Sophia and Hugh Auld: education, control, and moral corruption are central themes."],
        ["Slave narrative theme", "Slavery dehumanizes both enslaved and enslavers, but knowledge and moral reasoning enable resistance."]
      ]
    }
  }
  
export const tnofd79: AllSetsInterface = {
    "id": "tnofd-chatpers-7-through-9",
    "set": {
      "title": "Narrative of the Life of Frederick Douglass: Chapters VII-IX Study Guide",
      "vocab": [
        ["Self-education", "Douglass continues to learn reading and writing despite Mrs. Auld’s cessation of teaching."],
        ["Neighborhood boys", "Local boys who teach Douglass to read in exchange for bread, supporting his education and political awareness."],
        ["The Columbian Orator", "A book that helps Douglass articulate arguments against slavery and for human rights; contains dialogue and speeches."],
        ["Abolitionist", "Term Douglass learns means 'antislavery'; inspires thoughts of escape and freedom."],
        ["Escape plan", "Douglass contemplates fleeing North after encouragement from Irish sailors and his growing awareness of freedom."],
        ["Writing practice", "Douglass copies letters and words from carpenters, fences, walls, and discarded copybooks to learn writing."],
        ["Captain Anthony", "Douglass’s old master; dies during Douglass’s early years in Baltimore, triggering redistribution of slaves."],
        ["Valuation of enslaved people", "Enslaved people are appraised alongside livestock, emphasizing their treatment as property."],
        ["Master Andrew and Lucretia Auld", "Relatives who inherit enslaved people; Master Andrew is cruel, Lucretia returns Douglass to Baltimore."],
        ["Grandmother’s fate", "Abandoned in a hut in old age because slave owners value only productive labor."],
        ["Thomas Auld", "Acquires Douglass through marriage; inconsistent, cruel, and imitates slaveholding techniques poorly."],
        ["Religious conversion", "Auld’s conversion to Christianity intensifies cruelty, showing false religion as justification for oppression."],
        ["True vs. false Christianity", "Douglass contrasts genuinely religious, sympathetic individuals with those who use religion to justify slavery."],
        ["Urban freedom motif", "Baltimore offers Douglass relative freedom, intellectual growth, and interaction with supportive people."],
        ["Rural oppression motif", "Eastern Shore plantation represents harsh oversight, limited mobility, and dehumanization."],
        ["Education and awareness dilemma", "Learning to read increases Douglass’s knowledge of injustice but also his frustration and unhappiness."],
        ["Slaveholder role-playing", "Auld’s cruelty is partially an act to maintain authority; power is constructed through performance."],
        ["Ownership motif", "Repeated transfers of Douglass and other enslaved people show they are treated strictly as property."],
        ["Sentimental fiction technique", "Douglass imagines his grandmother’s suffering to evoke sympathy and political outrage."],
        ["Intellectual and political growth", "Douglass’s reading and discussions in Baltimore lead to self-education and political consciousness."],
        ["Education vs. physical freedom", "Intellectual enlightenment does not immediately confer freedom, highlighting the difference between mental and physical liberation."],
        ["Cruelty of adoptive slaveholders", "Thomas Auld exemplifies how those who inherit slaves often are harsher than native slaveholders."],
        ["Food scarcity and survival", "Enslaved people must beg or steal food from neighbors while owners waste supplies."],
        ["Edward Covey", "Known as a 'slave breaker'; Douglass is rented to him for a year, highlighting systemic cruelty and labor exploitation."],
        ["Chronological disruption", "Douglass arranges events thematically rather than strictly chronologically to emphasize motifs and lessons."],
        ["Education as political enlightenment", "Learning to read allows Douglass to understand slavery’s injustice and human rights issues."],
        ["Intellectual freedom vs. material freedom", "Douglass experiences growing political consciousness before he can physically escape slavery."],
        ["Slaveholding as unnatural", "Douglass portrays slavery as a role-played, unnatural system, exemplified by Thomas Auld’s awkward cruelty."],
        ["Slaveholder hypocrisy", "Auld uses religion falsely to justify cruelty, demonstrating the moral corruption of slavery."],
        ["Psychological insight", "Douglass observes how both urban and rural slavery, education, and religion shape the minds of enslaved and enslavers."],
        ["Reading as resistance", "Douglass’s literacy is both a tool for personal empowerment and a subtle form of rebellion."],
        ["Slave narrative structure", "Douglass blends autobiography, political argument, and imaginative reconstruction of scenes to persuade readers."],
        ["Mentorship and support", "Douglass relies on both sympathetic peers and strangers to gain knowledge and consider freedom options."],
        ["Moral and social education", "Douglass’s encounters with ideas and people in Baltimore expand his understanding of justice and oppression."],
        ["Urban-rural contrast", "The city is associated with freedom and intellectual growth; the countryside with surveillance, cruelty, and restriction."],
        ["Slave’s psychological doubling", "Douglass reflects on his past and present selves—his enslaved body and his intellectual, free self simultaneously."],
        ["Theme of hope and resilience", "Despite obstacles, Douglass nurtures determination to learn and eventually seek freedom."]
      ]
    }
  }

  export const tnofdx1: AllSetsInterface = {
    "id": "tnofd-chapter-10-part-1",
    "set": {
      "title": "Narrative of the Life of Frederick Douglass: Chapter X, Part 1 Study Guide",
      "vocab": [
        ["Edward Covey", "Slaveholder known as 'the snake'; cruel, deceitful, and physically abuses enslaved people to 'break' them."],
        ["First field work", "Douglass's initial experience guiding unbroken oxen, nearly losing his life due to inexperience."],
        ["Physical punishment", "Covey whips Douglass almost weekly as punishment for perceived awkwardness or failure."],
        ["Dehumanization", "Covey’s treatment reduces Douglass to a passive, fearful, and almost animal-like state."],
        ["Hard labor", "Douglass and other enslaved people work long hours in the fields with minimal breaks for food."],
        ["Covey’s piety", "Covey pretends religious devotion to justify cruelty; engages in sins like adultery."],
        ["Caroline", "A woman enslaved by Covey to serve as a 'breeder,' highlighting exploitation and abuse."],
        ["Sunday leisure", "Douglass’s only time of rest, often spent in mental stupor from exhaustion and despair."],
        ["Symbolism of ships", "Ships on the Chesapeake Bay represent freedom and contrast Douglass’s enslaved condition."],
        ["Self-doubt and despair", "Douglass contemplates suicide and reflects on the seeming absence of divine justice."],
        ["Physical confrontation", "Douglass fights Covey to regain dignity, control, and self-respect."],
        ["Sandy Jenkins", "Neighboring enslaved man who advises Douglass to carry a protective magical root."],
        ["Magical root", "Symbolic object representing traditional or superstitious belief; Douglass questions its efficacy."],
        ["Reclaiming agency", "Douglass asserts himself through controlled violence, regaining personal spirit and resistance."],
        ["Slave-to-man transformation", "Douglass frames his fight with Covey as a turning point, restoring human dignity."],
        ["Rhetorical climax", "Douglass uses the phrase 'You have seen how a man was made a slave; you shall see how a slave was made a man' to highlight reversal of fortune."],
        ["False Christianity", "Covey’s religion is used to justify his cruelty; Douglass critiques this as moral corruption caused by slavery."],
        ["Satanic imagery", "Covey’s nickname 'the snake' evokes Satan, emphasizing deceit and malevolence."],
        ["Controlled violence vs. vengeance", "Douglass’s fight is self-defensive, aiming to end abuse rather than seek revenge."],
        ["Psychological recovery", "Physical resistance allows Douglass to regain mental clarity, hope, and determination to be free."]
      ]
    }
  }
  
  export const tnofdx2: AllSetsInterface = {
    "id": "tnofd-chapter-10-part-2",
    "set": {
      "title": "Narrative of the Life of Frederick Douglass: Chapter X, Part 2 Study Guide",
      "vocab": [
        ["Resolution to escape", "Douglass and fellow enslaved people plan to flee to the North, facing great danger and uncertainty."],
        ["Holiday manipulation", "Slaveholders give enslaved people Christmas–New Year’s holidays with alcohol to suppress rebellious spirit."],
        ["William Freeland", "Fairer and more consistent master; lacks hypocritical religiosity and treats enslaved people relatively well."],
        ["Sabbath school", "Douglass secretly teaches other enslaved people to read; education is forbidden and dangerous."],
        ["Community solidarity", "Douglass relies on friendships and support from fellow enslaved people at Freeland’s."],
        ["Pun on 'Freeland'", "Douglass notes the irony that being under Freeland’s ownership is not equivalent to living on truly free land."],
        ["Escape party", "Group of enslaved people planning to flee: Douglass, Henry Harris, John Harris, Henry Bailey, and Charles Roberts."],
        ["Betrayal and capture", "Escape is foiled by an unknown betrayer; Douglass is jailed while others are released."],
        ["Thomas Auld", "Douglass’s former master who alternates between harshness and indecision regarding Douglass’s fate."],
        ["Apprenticeship to William Gardner", "Douglass begins learning ship caulking but serves as a helper to many carpenters without gaining skill initially."],
        ["Violence at shipyard", "White apprentices attack Douglass, nearly blinding him; legal system denies justice due to racial bias."],
        ["Hugh Auld’s legal intervention", "Hugh advocates for Douglass, but the law cannot protect a Black man without white testimony."],
        ["Apprenticeship under Walter Price", "Douglass learns caulking skillfully, earns highest wages, but must surrender them to Hugh Auld."],
        ["Labor as property", "Douglass contrasts paid labor with enslaved labor, highlighting injustice of turning wages over to master."],
        ["American rights vs. slavery", "Douglass exposes contradiction of being an 'American' yet denied legal and civil rights."],
        ["Patrick Henry reference", "Douglass compares enslaved people’s perilous choice to Henry’s 'Give me liberty or give me death,' emphasizing real-life stakes."],
        ["Heroic individualism vs. community support", "Douglass contrasts solitary hero narrative with the collective effort and solidarity among enslaved people."],
        ["Slaveholding as a perversion of Christianity", "Slave owners justify cruelty through religion; Freeland’s fairness shows absence of this hypocrisy does not make slavery just."],
        ["Doubtful liberty", "The risk of escape represents uncertain freedom versus near-certain oppression under slavery."],
        ["Motif of enslaved people as property", "Monetary and social control over Douglass emphasizes the dehumanizing view of slaves as commodities."]
      ]
    }
  }

  export const tnofdxi1: AllSetsInterface = {
    "id": "tnofd-chapter-11-part-1",
    "set": {
      "title": "Narrative of the Life of Frederick Douglass: Chapter XI, Part 1 Study Guide",
      "vocab": [
        ["Omission of escape details", "Douglass deliberately does not reveal how he escaped to prevent slaveholders from stopping future escapes."],
        ["Perpetuation of slavery through ignorance", "Slaveholders keep enslaved people powerless by restricting education; Douglass reverses this tactic on them."],
        ["Vindictive imagination", "Douglass imagines slaveholders panicking over unseen threats, showing a role reversal of fear and power."],
        ["Hugh Auld wage arrangement", "Douglass hires his own time, pays Auld weekly, gaining a taste of autonomy while under supervision."],
        ["Thomas Auld’s refusal", "Thomas Auld denies Douglass independent work, fearing it will enable escape."],
        ["Planning escape", "Douglass sets a specific date (September 3) to flee, while maintaining normal work to avoid suspicion."],
        ["Anxiety and farewells", "Douglass feels fear of failure and sadness at leaving friends and familiar life in Baltimore."],
        ["New York City arrival", "Douglass reaches freedom without revealing the methods of escape."],
        ["Protection of allies", "Douglass omits details to keep friends who aided him safe from retribution."],
        ["Individual success story", "Douglass presents his freedom as a personal accomplishment, emphasizing selfhood despite social bonds."],
        ["Theme of knowledge and power", "Lack of knowledge controls people; withholding information can shift power dynamics."],
        ["Balancing personal narrative and safety", "Douglass provides enough story for impact while protecting identities and methods."]
      ]
    }
  }
  
  export const tnofdxi2: AllSetsInterface = {
    "id": "tnofd-chapter-11-part-2",
    "set": {
      "title": "Narrative of the Life of Frederick Douglass: Chapter XI, Part 2 & Appendix Study Guide",
      "vocab": [
        ["Arrival in New York", "Douglass feels fear and isolation in an unfamiliar city, lacking money, food, shelter, and friends."],
        ["David Ruggles", "A free Black abolitionist who shelters Douglass, advises him to go to New Bedford, and gives him a letter of recommendation and five dollars."],
        ["Anna Murray", "Douglass's fiancée from Baltimore who joins him in New York, helping him establish a new life."],
        ["New Bedford", "A Northern city where Douglass works as a caulker, finds a supportive Black community, and experiences freedom."],
        ["Name change", "Mr. Nathan Johnson suggests 'Douglass,' giving him a sense of identity and self-determination after slavery stripped him of his original name."],
        ["Northern Black community", "Douglass observes prosperity, political awareness, education, mutual support, and protection for escaped slaves."],
        ["Employment and wages", "Douglass works in various jobs at the docks, eventually earning enough to subscribe to an abolitionist magazine."],
        ["Public speaking", "Douglass is encouraged to share his experience at an antislavery convention, marking the start of his career as an activist."],
        ["Trial of solitude", "Douglass’s first days in New York test his independence and ability to navigate life alone."],
        ["Identity and emancipation", "Claiming a new name symbolizes Douglass's self-assertion and step toward full freedom."],
        ["Critique of Southern Christianity", "Douglass contrasts the pure Christianity of Christ with the corrupt, hypocritical Christianity of slaveholders."],
        ["Religious and literary allusions", "Douglass uses biblical and poetic references in the appendix to strengthen his moral and rhetorical arguments against slavery."],
        ["Mastery over language", "By interpreting texts and crafting arguments, Douglass demonstrates intellectual and personal sovereignty denied under slavery."]
      ]
    }
  }
  
  
  