export const data = {
    "title": "Tema 1 - Las familias y las comunidades",
    "vocab": [
      ["(bien) educado", "well-mannered"],
      ["agradecer", "to thank"],
      ["apoyar(se)", "to support (each other)"],
      ["criar", "to raise (children)"],
      ["egoísta", "selfish"],
      ["el apodo", "nickname"],
      ["el carácter", "character, personality"],
      ["el nacimiento", "birth"],
      ["el padrastro", "stepfather"],
      ["el prejuicio social", "social prejudice"],
      ["el sexo", "gender"],
      ["el tatarabuelo", "great-great grandfather"],
      ["el yerno", "son-in-law"],
      ["el/la adolescente", "adolescent"],
      ["el/la adulto", "adult"],
      ["el/la bisabuelo", "great-grandfather/mother"],
      ["el/la cuñado", "brother/sister-in-law"],
      ["el/la esposo", "husband/wife"],
      ["el/la hermanastro", "stepbrother/sister"],
      ["el/la hermano (gemelo)", "sister/brother (twin)"],
      ["el/la hijo único", "only child"],
      ["el/la medio hermano", "half brother/sister"],
      ["el/la nieto", "grandson/daughter"],
      ["el/la niña", "child"],
      ["el/la pariente/a", "relative"],
      ["el/la primo", "cousin"],
      ["el/la sobrino", "nephew/niece"],
      ["el/la suegro", "father/mother-in-law"],
      ["el/la tío (abuelo)", "(great) uncle/aunt"],
      ["estricto", "strict"],
      ["exigente", "demanding"],
      ["fastidiado", "fed up/bored"],
      ["heredar", "to inherit"],
      ["honrado", "honest"],
      ["independizarse", "to become independent"],
      ["insoportable", "unbearable"],
      ["la adolescencia", "adolescence"],
      ["la ascendencia", "heritage"],
      ["la autoestima", "self-esteem"],
      ["la brecha generacional", "generational gap"],
      ["la comprensión", "understanding"],
      ["la edad adulta", "adulthood"],
      ["la etnia", "ethnic group"],
      ["la juventud", "youth"],
      ["la madrastra", "stepmother"],
      ["la muerte", "death"],
      ["la niñez", "childhood"],
      ["la nuera", "daughter-in-law"],
      ["la patria", "homeland"],
      ["la raíz", "root"],
      ["la vejez", "old age"],
      ["lamentar", "to regret"],
      ["malcriar", "to spoil"],
      ["maleducado", "ill-mannered"],
      ["mandón/mandona", "bossy"],
      ["mimar", "to pamper"],
      ["mudarse", "to move"],
      ["parecerse", "to resemble, to look like"],
      ["pelear(se)", "to fight (with one another)"]
    ]
  }
  