interface VocabularySet  {
    title: string;
    vocab: [string, string][]; 
    filters: string[];
}

export const allFilters: string[] = [
  "Spanish",
  "French",
  "Japanese",
  "Programming",
  "Science",
  "Geography",
  "Music",
  "Mathematics",
  "Art",
  "History"
];

export const vocabularySets: VocabularySet[] = [
    {
      title: "Basic Spanish Greetings and Phrases",
      vocab: [
        ["Hello", "Hola"],
        ["Goodbye", "Adiós"],
        ["Good morning", "Buenos días"],
        ["Good afternoon", "Buenas tardes"],
        ["Good night", "Buenas noches"],
        ["How are you?", "¿Cómo estás?"],
        ["I'm fine", "Estoy bien"],
        ["Thank you", "Gracias"],
        ["You're welcome", "De nada"],
        ["Please", "Por favor"],
        ["Nice to meet you", "Mucho gusto"],
        ["See you later", "Hasta luego"],
        ["What's your name?", "¿Cómo te llamas?"],
        ["My name is...", "Me llamo..."],
        ["I don't understand", "No entiendo"],
        ["Do you speak English?", "¿Hablas inglés?"],
      ],
      filters: ["Spanish", "Greetings", "Beginner", "Conversation"]
    },
    {
      title: "French Food and Dining Vocabulary",
      vocab: [
        ["Bread", "Pain"],
        ["Cheese", "Fromage"],
        ["Wine", "Vin"],
        ["Apple", "Pomme"],
        ["Dinner", "Dîner"],
        ["Restaurant", "Restaurant"],
        ["Menu", "Menu"],
        ["Waiter", "Serveur"],
        ["Fork", "Fourchette"],
        ["Knife", "Couteau"],
        ["Spoon", "Cuillère"],
        ["Plate", "Assiette"],
        ["Glass", "Verre"],
        ["Vegetarian", "Végétarien"],
        ["Delicious", "Délicieux"],
        ["Bill", "Addition"],
      ],
      filters: ["French", "Food", "Dining", "Intermediate"]
    },
    {
      title: "Basic German Phrases and Questions",
      vocab: [
        ["Please", "Bitte"],
        ["Thank you", "Danke"],
        ["You're welcome", "Bitte schön"],
        ["Excuse me", "Entschuldigung"],
        ["I don't understand", "Ich verstehe nicht"],
        ["Do you speak English?", "Sprechen Sie Englisch?"],
        ["Where is...?", "Wo ist...?"],
        ["How much?", "Wie viel?"],
        ["What time is it?", "Wie spät ist es?"],
        ["Good morning", "Guten Morgen"],
        ["Good evening", "Guten Abend"],
        ["Goodbye", "Auf Wiedersehen"],
        ["Yes", "Ja"],
        ["No", "Nein"],
        ["My name is...", "Ich heiße..."],
        ["Nice to meet you", "Freut mich, Sie kennenzulernen"],
      ],
      filters: ["German", "Phrases", "Beginner", "Conversation"]
    },
    // ... (other sets follow the same pattern)
    {
      title: "Weather Terms and Descriptions",
      vocab: [
        ["Sunny", "Clear sky with bright sunlight"],
        ["Cloudy", "Sky covered with clouds"],
        ["Rainy", "Falling water droplets from the sky"],
        ["Windy", "Strong movement of air"],
        ["Foggy", "Low-lying clouds reducing visibility"],
        ["Snowy", "Falling ice crystals from the sky"],
        ["Stormy", "Severe weather with strong winds, rain, and possibly thunder and lightning"],
        ["Humid", "Air containing a high amount of water vapor"],
        ["Dry", "Lacking moisture in the air"],
        ["Hail", "Falling pellets of frozen rain"],
        ["Sleet", "A mixture of rain and snow"],
        ["Tornado", "A violently rotating column of air that touches the ground"],
        ["Hurricane", "A large, rotating tropical storm with high winds and heavy rain"],
        ["Breeze", "A gentle wind"],
        ["Overcast", "Sky completely covered by clouds"],
        ["Drizzle", "Light rain falling in very fine drops"],
      ],
      filters: ["Weather", "Nature", "English", "Descriptions"]
    },
    {
      title: "Greek Alphabet",
      vocab: [
        ["Alpha", "Α, α"],
        ["Beta", "Β, β"],
        ["Gamma", "Γ, γ"],
        ["Delta", "Δ, δ"],
        ["Epsilon", "Ε, ε"],
        ["Zeta", "Ζ, ζ"],
        ["Eta", "Η, η"],
        ["Theta", "Θ, θ"],
        ["Iota", "Ι, ι"],
        ["Kappa", "Κ, κ"],
        ["Lambda", "Λ, λ"],
        ["Mu", "Μ, μ"],
        ["Nu", "Ν, ν"],
        ["Xi", "Ξ, ξ"],
        ["Omicron", "Ο, ο"],
        ["Pi", "Π, π"],
      ],
      filters: ["Greek", "Alphabet", "Language", "Symbols"]
    },
    {
        title: "Basic Japanese Greetings and Phrases",
        vocab: [
          ["Hello", "こんにちは (Konnichiwa)"],
          ["Goodbye", "さようなら (Sayōnara)"],
          ["Good morning", "おはようございます (Ohayō gozaimasu)"],
          ["Good afternoon", "こんにちは (Konnichiwa)"],
          ["Good night", "おやすみなさい (Oyasuminasai)"],
          ["How are you?", "お元気ですか？ (Ogenki desu ka?)"],
          ["I'm fine", "元気です (Genki desu)"],
          ["Thank you", "ありがとう (Arigatō)"],
          ["You're welcome", "どういたしまして (Dōitashimashite)"],
          ["Please", "お願いします (Onegaishimasu)"],
          ["Nice to meet you", "初めまして (Hajimemashite)"],
          ["See you later", "じゃね (Ja ne)"],
          ["What's your name?", "お名前は何ですか？ (Onamae wa nan desu ka?)"],
          ["My name is...", "私の名前は...です (Watashi no namae wa...desu)"],
          ["I don't understand", "わかりません (Wakarimasen)"],
          ["Do you speak English?", "英語を話せますか？ (Eigo o hanasemasu ka?)"],
        ],
        filters: ["Japanese", "Greetings", "Beginner", "Conversation"]
      },
      {
        title: "Italian Travel Vocabulary",
        vocab: [
          ["Airport", "Aeroporto"],
          ["Hotel", "Hotel"],
          ["Train station", "Stazione ferroviaria"],
          ["Ticket", "Biglietto"],
          ["Passport", "Passaporto"],
          ["Luggage", "Bagaglio"],
          ["Reservation", "Prenotazione"],
          ["Map", "Mappa"],
          ["Bus", "Autobus"],
          ["Taxi", "Taxi"],
          ["Guide", "Guida"],
          ["Tour", "Tour"],
          ["Information", "Informazioni"],
          ["Help", "Aiuto"],
          ["Emergency", "Emergenza"],
        ],
        filters: ["Italian", "Travel", "Vocabulary", "Intermediate"]
      },
      {
        title: "Advanced Russian Verbs",
        vocab: [
          ["To write", "писать (pisat')"],
          ["To read", "читать (chitat')"],
          ["To speak", "говорить (govorit')"],
          ["To listen", "слушать (slushat')"],
          ["To eat", "есть (yest')"],
          ["To drink", "пить (pit')"],
          ["To work", "работать (rabotat')"],
          ["To study", "учиться (uchit'sya)"],
          ["To travel", "путешествовать (puteshestvovat')"],
          ["To help", "помогать (pomogat')"],
          ["To learn", "учить (uchit')"],
          ["To understand", "понимать (ponimat')"],
          ["To teach", "научить (nauchit')"],
          ["To sleep", "спать (spat')"],
          ["To know", "знать (znat')"],
        ],
        filters: ["Russian", "Verbs", "Advanced", "Grammar"]
      },
      {
        title: "Spanish Numbers and Quantities",
        vocab: [
          ["One", "Uno"],
          ["Two", "Dos"],
          ["Three", "Tres"],
          ["Four", "Cuatro"],
          ["Five", "Cinco"],
          ["Ten", "Diez"],
          ["Hundred", "Cien"],
          ["Thousand", "Mil"],
          ["First", "Primero"],
          ["Second", "Segundo"],
          ["Third", "Tercero"],
          ["Many", "Muchos"],
          ["Few", "Pocos"],
          ["None", "Ninguno"],
          ["Some", "Algunos"],
        ],
        filters: ["Spanish", "Numbers", "Quantities", "Basic"]
      },
      {
        title: "Medical Terms and Conditions",
        vocab: [
          ["Doctor", "Medico"],
          ["Nurse", "Infermiere"],
          ["Hospital", "Ospedale"],
          ["Medicine", "Farmaco"],
          ["Pain", "Dolore"],
          ["Fever", "Febbre"],
          ["Infection", "Infezione"],
          ["Appointment", "Appuntamento"],
          ["Symptom", "Sintomo"],
          ["Diagnosis", "Diagnosi"],
          ["Treatment", "Trattamento"],
          ["Prescription", "Ricetta"],
          ["Surgery", "Chirurgia"],
          ["Recovery", "Ripresa"],
          ["Health", "Salute"],
        ],
        filters: ["Medical", "Terms", "Health", "Italian"]
      }
  ];